// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

// Code generated by cmd/counterprobe -mode world-emit. DO NOT EDIT;
// regenerate with go run ./cmd/counterprobe -geodata data/geodata
// -mode world-emit (the world stand round of 2026-09-20: 93 world
// merchant spawns probed, 58 answered by the spawn fallback, 27
// derived and grid verified here, the 8 curated counter rows of
// merchantStands re-verified and kept there, 0 failed).

package hunt

import "github.com/melg8/swarm/internal/swarm/pathfind"

// merchantStandsWorld carries the customer stand points the counterprobe
// world pass derived and verified for the world merchants whose spawn
// cell the geodata pack does not serve (the roofed stall interiors, the
// counter fronts, the walled shop interiors - the spawn cell answers no
// walkable floor or no verified route onto it). Every row sits within
// the interaction distance of its spawn, on the spawn's own floor
// scale, with the grid route and the line of sight of every leg pinned
// by the pass (the count after the row names the independent approach
// directions that verified). The spawns the pack serves directly and
// the flat placeholder regions (Talking Island) stay out - the spawn
// fallback of merchantStandPoint answers them.

var merchantStandsWorld = map[int32]pathfind.Vec3{
    7081: {X: 80454, Y: 147922, Z: -3504},   // Helvetia, heading push, 2 ways
    7082: {X: 80454, Y: 147873, Z: -3504},   // Denkus, heading push, 2 ways
    7084: {X: 79747, Y: 146556, Z: -3520},   // Graham, heading push, 2 ways
    7085: {X: 79801, Y: 146557, Z: -3520},   // Stanford, heading push, 2 ways
    7087: {X: 79711, Y: 150724, Z: -3512},   // Peta, heading push, 2 ways
    7088: {X: 79654, Y: 150724, Z: -3512},   // Radia, heading push, 2 ways
    7090: {X: 80447, Y: 149183, Z: -3504},   // Sandra, heading push, 2 ways
    7091: {X: 80446, Y: 149250, Z: -3504},   // Ellie, heading push, 2 ways
    7135: {X: 10761, Y: 17906, Z: -4552},    // Iria, heading push, 2 ways
    7136: {X: 10882, Y: 17989, Z: -4552},    // Payne, heading push, 2 ways
    7137: {X: 11887, Y: 15661, Z: -4552},    // Vollodos, ring 64 W, 2 ways
    7138: {X: 12054, Y: 15749, Z: -4552},    // Minaless, ring 64 SE, 2 ways
    7178: {X: 79191, Y: 53657, Z: -1544},    // Zenkin, ring 80 E, 2 ways
    7179: {X: 79192, Y: 53602, Z: -1544},    // Raudia, ring 80 E, 2 ways
    7180: {X: 79531, Y: 54973, Z: -1544},    // Sara, ring 80 E, 2 ways
    7181: {X: 79531, Y: 54877, Z: -1544},    // Galibredo, ring 80 E, 2 ways
    7207: {X: -80343, Y: 154961, Z: -3160},  // Arodin, heading push, 2 ways
    7208: {X: -80871, Y: 155526, Z: -3160},  // Damion, heading push, 2 ways
    7253: {X: -15132, Y: 123362, Z: -3104},  // Simplon, ring 80 S, 2 ways
    7254: {X: -14854, Y: 124468, Z: -3112},  // Harmony, ring 80 E, 2 ways
    7294: {X: -14853, Y: 124540, Z: -3112},  // Varan, ring 80 E, 2 ways
    7314: {X: -80028, Y: 153307, Z: -3160},  // Nestle, ring 80 E, 1 ways
    7315: {X: -79405, Y: 153883, Z: -3160},  // Poesia, ring 80 N, 2 ways
    7321: {X: -15238, Y: 123362, Z: -3104},  // Sydnia, ring 80 S, 2 ways
    7516: {X: 115786, Y: -181600, Z: -1336}, // Reep, heading push, 2 ways
    7560: {X: -43963, Y: -115554, Z: -216},  // Uska, heading push, 2 ways
    7561: {X: -44003, Y: -115493, Z: -216},  // Papuma, heading push, 2 ways
}
