// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

// Code generated by tools/generate_hunt_spots.py from the committed zone registry;
// DO NOT EDIT by hand - re-run the generator instead. The
// spot registry replaces the square zone ladder of
// zones_elven.go: every spot is an anchor on the spawn mass
// (the grid adjacency clustering of the registry squares) with
// a visibility-bounded radius (<= 2048, the guaranteed
// knownlist circle of a standing character), the composition
// of the ground it covers and the respawn window of its mobs.
// See docs/hunting_system_redesign.md for the model.

package hunt

// elvenHuntingSpots anchors the elven lands in 71 hunting
// spots. The first entry is the starter fallback of the
// spot picker (the village nearest spot of the lowest band).
var elvenHuntingSpots = []Spot{
	{
		ID: "elven-spot-22", Name: "Red Keltir SE",
		Region: regionElven, MinLevel: 1, MaxLevel: 3,
		AnchorX: 48083, AnchorY: 43069, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 7.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20530, Name: "Young Red Keltir",
				Level: 1, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-46", Name: "Elder Red Keltir SW",
		Region: regionElven, MinLevel: 1, MaxLevel: 3,
		AnchorX: 43936, AnchorY: 43024, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 8.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20530, Name: "Young Red Keltir",
				Level: 1, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-72", Name: "Red Keltir W",
		Region: regionElven, MinLevel: 1, MaxLevel: 3,
		AnchorX: 41658, AnchorY: 41591, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 7.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20530, Name: "Young Red Keltir",
				Level: 1, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-71", Name: "Red Keltir NW",
		Region: regionElven, MinLevel: 1, MaxLevel: 3,
		AnchorX: 40888, AnchorY: 39028, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 7.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20530, Name: "Young Red Keltir",
				Level: 1, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-24", Name: "Red Keltir E",
		Region: regionElven, MinLevel: 1, MaxLevel: 3,
		AnchorX: 52564, AnchorY: 41814, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 5.2,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20530, Name: "Young Red Keltir",
				Level: 1, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-59", Name: "Elder Red Keltir NE",
		Region: regionElven, MinLevel: 2, MaxLevel: 3,
		AnchorX: 47872, AnchorY: 37504, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-49", Name: "Elder Red Keltir NW",
		Region: regionElven, MinLevel: 2, MaxLevel: 3,
		AnchorX: 44291, AnchorY: 37332, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-23", Name: "Elder Red Keltir NE",
		Region: regionElven, MinLevel: 2, MaxLevel: 3,
		AnchorX: 50332, AnchorY: 38493, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 4.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-25", Name: "Gray Wolf E",
		Region: regionElven, MinLevel: 2, MaxLevel: 4,
		AnchorX: 52887, AnchorY: 41157, Radius: 1556,
		RespawnMin: 15, RespawnMax: 20, Mass: 3.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20534, Name: "Red Keltir",
				Level: 2, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-58", Name: "Gray Wolf N",
		Region: regionElven, MinLevel: 3, MaxLevel: 4,
		AnchorX: 46270, AnchorY: 35058, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 8.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-66", Name: "Gray Wolf W",
		Region: regionElven, MinLevel: 3, MaxLevel: 4,
		AnchorX: 39040, AnchorY: 41727, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-48", Name: "Gray Wolf NW",
		Region: regionElven, MinLevel: 3, MaxLevel: 4,
		AnchorX: 42424, AnchorY: 34387, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 7.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-47", Name: "Gray Wolf NW",
		Region: regionElven, MinLevel: 3, MaxLevel: 4,
		AnchorX: 39468, AnchorY: 35920, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 8.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-57", Name: "Elder Red Keltir W",
		Region: regionElven, MinLevel: 3, MaxLevel: 4,
		AnchorX: 37890, AnchorY: 38586, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 8.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20537, Name: "Elder Red Keltir",
				Level: 3, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-21", Name: "Goblin Raider SE",
		Region: regionElven, MinLevel: 4, MaxLevel: 5,
		AnchorX: 50659, AnchorY: 46248, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 11.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 7, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-60", Name: "Gray Wolf SW",
		Region: regionElven, MinLevel: 4, MaxLevel: 5,
		AnchorX: 38913, AnchorY: 52587, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-50", Name: "Gray Wolf SW",
		Region: regionElven, MinLevel: 4, MaxLevel: 5,
		AnchorX: 39461, AnchorY: 54803, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 9.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 6, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-03", Name: "Goblin Raider S",
		Region: regionElven, MinLevel: 4, MaxLevel: 5,
		AnchorX: 48771, AnchorY: 56339, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-01", Name: "Goblin Raider SE",
		Region: regionElven, MinLevel: 4, MaxLevel: 6,
		AnchorX: 53504, AnchorY: 45249, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 11.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20468, Name: "Kaboo Orc",
				Level: 6, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-02", Name: "Gray Wolf SE",
		Region: regionElven, MinLevel: 4, MaxLevel: 6,
		AnchorX: 52738, AnchorY: 55386, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20468, Name: "Kaboo Orc",
				Level: 6, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-04", Name: "Kaboo Orc S",
		Region: regionElven, MinLevel: 4, MaxLevel: 6,
		AnchorX: 51147, AnchorY: 59548, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 9.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20468, Name: "Kaboo Orc",
				Level: 6, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20525, Name: "Gray Wolf",
				Level: 4, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-27", Name: "Kaboo Orc Grunt SE",
		Region: regionElven, MinLevel: 5, MaxLevel: 7,
		AnchorX: 51558, AnchorY: 50575, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20470, Name: "Kaboo Orc Grunt",
				Level: 7, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20468, Name: "Kaboo Orc",
				Level: 6, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-28", Name: "Kaboo Orc SE",
		Region: regionElven, MinLevel: 5, MaxLevel: 7,
		AnchorX: 54254, AnchorY: 50639, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 10.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20470, Name: "Kaboo Orc Grunt",
				Level: 7, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20468, Name: "Kaboo Orc",
				Level: 6, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20325, Name: "Goblin Raider",
				Level: 5, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-67", Name: "Kaboo Orc Grunt SW",
		Region: regionElven, MinLevel: 7, MaxLevel: 8,
		AnchorX: 38553, AnchorY: 50080, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 14.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20336, Name: "Green Dryad",
				Level: 8, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20470, Name: "Kaboo Orc Grunt",
				Level: 7, Count: 7, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-26", Name: "Kaboo Orc Grunt S",
		Region: regionElven, MinLevel: 7, MaxLevel: 8,
		AnchorX: 42278, AnchorY: 56761, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 15.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20336, Name: "Green Dryad",
				Level: 8, Count: 6, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20470, Name: "Kaboo Orc Grunt",
				Level: 7, Count: 7, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-05", Name: "Kaboo Orc Grunt S",
		Region: regionElven, MinLevel: 7, MaxLevel: 8,
		AnchorX: 44182, AnchorY: 60944, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.8,
		Mobs: []SpotMob{
			{
				TemplateID: 20336, Name: "Green Dryad",
				Level: 8, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20470, Name: "Kaboo Orc Grunt",
				Level: 7, Count: 6, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-68", Name: "Kaboo Orc Fighter SW",
		Region: regionElven, MinLevel: 7, MaxLevel: 10,
		AnchorX: 35214, AnchorY: 51358, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20470, Name: "Kaboo Orc Grunt",
				Level: 7, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-32", Name: "Spore Fungus SW",
		Region: regionElven, MinLevel: 7, MaxLevel: 10,
		AnchorX: 35414, AnchorY: 55403, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 14.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 6, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20470, Name: "Kaboo Orc Grunt",
				Level: 7, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-30", Name: "Spore Fungus SW",
		Region: regionElven, MinLevel: 8, MaxLevel: 10,
		AnchorX: 38339, AnchorY: 46052, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 13.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20336, Name: "Green Dryad",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-29", Name: "Spore Fungus SW",
		Region: regionElven, MinLevel: 8, MaxLevel: 10,
		AnchorX: 35292, AnchorY: 46424, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 14.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 6, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-31", Name: "Kaboo Orc Fighter SW",
		Region: regionElven, MinLevel: 8, MaxLevel: 10,
		AnchorX: 37416, AnchorY: 59038, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 9.6,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20336, Name: "Green Dryad",
				Level: 8, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-06", Name: "Kaboo Orc Fighter W",
		Region: regionElven, MinLevel: 8, MaxLevel: 10,
		AnchorX: 24859, AnchorY: 37654, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-33", Name: "Spore Fungus S",
		Region: regionElven, MinLevel: 8, MaxLevel: 10,
		AnchorX: 39199, AnchorY: 61983, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20336, Name: "Green Dryad",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-36", Name: "Spore Fungus SW",
		Region: regionElven, MinLevel: 8, MaxLevel: 10,
		AnchorX: 34575, AnchorY: 61654, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 21.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 8, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 10, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-34", Name: "Spore Fungus S",
		Region: regionElven, MinLevel: 8, MaxLevel: 10,
		AnchorX: 41508, AnchorY: 64502, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20336, Name: "Green Dryad",
				Level: 8, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20469, Name: "Kaboo Orc Archer",
				Level: 8, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-35", Name: "Spore Fungus SW",
		Region: regionElven, MinLevel: 9, MaxLevel: 9,
		AnchorX: 31700, AnchorY: 55825, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 3.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-39", Name: "Spore Fungus SW",
		Region: regionElven, MinLevel: 9, MaxLevel: 9,
		AnchorX: 26552, AnchorY: 63547, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 3.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-07", Name: "Spore Fungus SW",
		Region: regionElven, MinLevel: 9, MaxLevel: 11,
		AnchorX: 31455, AnchorY: 48531, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 13.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-08", Name: "Kaboo Orc Fighter W",
		Region: regionElven, MinLevel: 9, MaxLevel: 11,
		AnchorX: 25268, AnchorY: 41138, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 11.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-37", Name: "Kaboo Orc Fighter Lieutenant SW",
		Region: regionElven, MinLevel: 9, MaxLevel: 11,
		AnchorX: 31134, AnchorY: 62229, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 13.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-09", Name: "Kaboo Orc Fighter Leader W",
		Region: regionElven, MinLevel: 9, MaxLevel: 12,
		AnchorX: 19941, AnchorY: 40396, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-52", Name: "Kaboo Orc Fighter Leader W",
		Region: regionElven, MinLevel: 9, MaxLevel: 13,
		AnchorX: 19400, AnchorY: 43433, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 10.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20509, Name: "Spore Fungus",
				Level: 9, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-51", Name: "Kaboo Orc Fighter Lieutenant SW",
		Region: regionElven, MinLevel: 10, MaxLevel: 11,
		AnchorX: 28756, AnchorY: 55735, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 3.2,
		Mobs: []SpotMob{
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20471, Name: "Kaboo Orc Fighter",
				Level: 10, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-38", Name: "Kaboo Orc Fighter Lieutenant SW",
		Region: regionElven, MinLevel: 11, MaxLevel: 12,
		AnchorX: 26907, AnchorY: 63452, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 5.5,
		Mobs: []SpotMob{
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-10", Name: "Kaboo Orc Fighter Lieutenant SW",
		Region: regionElven, MinLevel: 11, MaxLevel: 13,
		AnchorX: 25870, AnchorY: 50783, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 14.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 6, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-40", Name: "Kaboo Orc Fighter Leader W",
		Region: regionElven, MinLevel: 11, MaxLevel: 13,
		AnchorX: 22307, AnchorY: 46530, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 14.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20473, Name: "Kaboo Orc Fighter Lieutenant",
				Level: 11, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-70", Name: "Dryad SW",
		Region: regionElven, MinLevel: 12, MaxLevel: 13,
		AnchorX: 24934, AnchorY: 59076, Radius: 1756,
		RespawnMin: 15, RespawnMax: 20, Mass: 2.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-63", Name: "Dryad W",
		Region: regionElven, MinLevel: 12, MaxLevel: 13,
		AnchorX: 17157, AnchorY: 46089, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 2.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-69", Name: "Kaboo Orc Fighter Leader SW",
		Region: regionElven, MinLevel: 12, MaxLevel: 14,
		AnchorX: 24162, AnchorY: 59111, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.5,
		Mobs: []SpotMob{
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-41", Name: "Kaboo Orc Fighter Leader W",
		Region: regionElven, MinLevel: 12, MaxLevel: 14,
		AnchorX: 17990, AnchorY: 49828, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 10.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-53", Name: "Kaboo Orc Fighter Leader W",
		Region: regionElven, MinLevel: 12, MaxLevel: 14,
		AnchorX: 16884, AnchorY: 52856, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 7.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-11", Name: "Kaboo Orc Fighter Leader W",
		Region: regionElven, MinLevel: 12, MaxLevel: 14,
		AnchorX: 12454, AnchorY: 47625, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 9.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-12", Name: "Dryad Elder SW",
		Region: regionElven, MinLevel: 12, MaxLevel: 15,
		AnchorX: 18182, AnchorY: 57020, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.5,
		Mobs: []SpotMob{
			{
				TemplateID: 20460, Name: "Crimson Spider",
				Level: 15, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20472, Name: "Kaboo Orc Fighter Leader",
				Level: 12, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-61", Name: "Dryad SW",
		Region: regionElven, MinLevel: 13, MaxLevel: 13,
		AnchorX: 28024, AnchorY: 57840, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 3.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-55", Name: "Crimson Spider W",
		Region: regionElven, MinLevel: 13, MaxLevel: 15,
		AnchorX: 9226, AnchorY: 49297, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20460, Name: "Crimson Spider",
				Level: 15, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20013, Name: "Dryad",
				Level: 13, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-54", Name: "Crimson Spider W",
		Region: regionElven, MinLevel: 14, MaxLevel: 15,
		AnchorX: 15936, AnchorY: 52218, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 3.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20460, Name: "Crimson Spider",
				Level: 15, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 1, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-14", Name: "Dryad Elder SW",
		Region: regionElven, MinLevel: 14, MaxLevel: 16,
		AnchorX: 12638, AnchorY: 59812, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 7.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20460, Name: "Crimson Spider",
				Level: 15, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-13", Name: "Hook Spider SW",
		Region: regionElven, MinLevel: 14, MaxLevel: 16,
		AnchorX: 10929, AnchorY: 56364, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 13.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20460, Name: "Crimson Spider",
				Level: 15, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-42", Name: "Dryad Elder W",
		Region: regionElven, MinLevel: 14, MaxLevel: 16,
		AnchorX: 6171, AnchorY: 52368, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 10.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20460, Name: "Crimson Spider",
				Level: 15, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20019, Name: "Dryad Elder",
				Level: 14, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-44", Name: "Lirein SW",
		Region: regionElven, MinLevel: 16, MaxLevel: 18,
		AnchorX: 9722, AnchorY: 63285, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 9.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-43", Name: "Hook Spider SW",
		Region: regionElven, MinLevel: 16, MaxLevel: 18,
		AnchorX: 6826, AnchorY: 59986, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 13.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-15", Name: "Lirein W",
		Region: regionElven, MinLevel: 16, MaxLevel: 18,
		AnchorX: 3849, AnchorY: 55943, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 11.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-16", Name: "Pincer Spider SW",
		Region: regionElven, MinLevel: 16, MaxLevel: 18,
		AnchorX: 7051, AnchorY: 66490, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 7.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-64", Name: "Lirein SW",
		Region: regionElven, MinLevel: 16, MaxLevel: 18,
		AnchorX: 6396, AnchorY: 71742, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 11.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-65", Name: "Lirein SW",
		Region: regionElven, MinLevel: 16, MaxLevel: 18,
		AnchorX: 4544, AnchorY: 74493, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20308, Name: "Hook Spider",
				Level: 16, Count: 2, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-17", Name: "Pincer Spider SW",
		Region: regionElven, MinLevel: 17, MaxLevel: 19,
		AnchorX: 3052, AnchorY: 62860, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 14.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20044, Name: "Lirein Elder",
				Level: 19, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 7, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-18", Name: "Pincer Spider SW",
		Region: regionElven, MinLevel: 17, MaxLevel: 19,
		AnchorX: 2100, AnchorY: 67480, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 12.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20044, Name: "Lirein Elder",
				Level: 19, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-56", Name: "Pincer Spider SW",
		Region: regionElven, MinLevel: 17, MaxLevel: 19,
		AnchorX: 2500, AnchorY: 72343, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 10.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20044, Name: "Lirein Elder",
				Level: 19, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 4, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-45", Name: "Lirein Elder SW",
		Region: regionElven, MinLevel: 17, MaxLevel: 19,
		AnchorX: 4868, AnchorY: 77104, Radius: 1656,
		RespawnMin: 15, RespawnMax: 20, Mass: 6.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20044, Name: "Lirein Elder",
				Level: 19, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 3, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-19", Name: "Pincer Spider SW",
		Region: regionElven, MinLevel: 17, MaxLevel: 19,
		AnchorX: 5069, AnchorY: 82406, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 15.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20044, Name: "Lirein Elder",
				Level: 19, Count: 7, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20466, Name: "Pincer Spider",
				Level: 17, Count: 8, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
	{
		ID: "elven-spot-20", Name: "Lirein Elder SW",
		Region: regionElven, MinLevel: 18, MaxLevel: 19,
		AnchorX: 1708, AnchorY: 77534, Radius: 2048,
		RespawnMin: 15, RespawnMax: 20, Mass: 11.0,
		Mobs: []SpotMob{
			{
				TemplateID: 20044, Name: "Lirein Elder",
				Level: 19, Count: 6, RespawnMin: 15, RespawnMax: 20,
			},
			{
				TemplateID: 20036, Name: "Lirein",
				Level: 18, Count: 5, RespawnMin: 15, RespawnMax: 20,
			},
		},
	},
}

// ElvenHuntingSpots returns the hunting spots of the elven lands.
func ElvenHuntingSpots() []Spot {
	spots := make([]Spot, len(elvenHuntingSpots))
	copy(spots, elvenHuntingSpots)

	return spots
}
