// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

// Code generated by tools/generate_hunt_zones.py from the Mobius C1
// spawn data (the Dion spawn sources of the 20-25 band survey -
// ExecutionGrounds, CrumaMarshlands, PlainsOfDion); DO NOT EDIT by
// hand - re-run the generator instead. The registry covers the spawn
// polygons with one or several compact squares per territory, every
// square carrying the full mob list of its territory (all species
// farmed, the level sorted priorities bias the engage toward the exp
// rich mobs).

package hunt

// dionHuntingZones ladders the Dion grounds of the 20-25 band in
// five mob level bands over 75 compact squares generated from the
// 25 kept spawn territories of the Dion spawn sources
// (ExecutionGrounds, CrumaMarshlands, PlainsOfDion - the survey
// of docs/band_20_25_survey.md; the same-band sub territories fold
// into their parents). The squares sit on the real spawn ground: the
// mobs of a territory spawn at uniformly random points of its polygon
// (NpcSpawnTerritory.getRandomPoint) and the wander stays inside the
// polygon, so the measured spawn mass coverage of this registry is
// 96%. The first entry is the starter fallback of the picker
// (the execution ground arrival nearest square of the 20-21 band).
var dionHuntingZones = []HuntingZone{
	{
		ID: "dion-2122_19-b1", Name: "Mandragora Sprout W-b1",
		Region: regionDion, MinLevel: 20, MaxLevel: 21, MinGear: 280,
		CX: 40191, CY: 149832, Half: 1600,
		Mobs: []ZoneMob{
			{
				TemplateID: 20154, Name: "Mandragora Sprout",
				Level: 21, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20223, Name: "Mandragora Sprout",
				Level: 20, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_18-b1", Name: "Mandragora Sprout NW-b1",
		Region: regionDion, MinLevel: 20, MaxLevel: 21, MinGear: 280,
		CX: 40249, CY: 146140, Half: 1500,
		Mobs: []ZoneMob{
			{
				TemplateID: 20154, Name: "Mandragora Sprout",
				Level: 21, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20223, Name: "Mandragora Sprout",
				Level: 20, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_19-a1", Name: "Mandragora Sprout W-a1",
		Region: regionDion, MinLevel: 20, MaxLevel: 21, MinGear: 280,
		CX: 37858, CY: 149720, Half: 1600,
		Mobs: []ZoneMob{
			{
				TemplateID: 20154, Name: "Mandragora Sprout",
				Level: 21, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20223, Name: "Mandragora Sprout",
				Level: 20, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_18-a1", Name: "Mandragora Sprout NW-a1",
		Region: regionDion, MinLevel: 20, MaxLevel: 21, MinGear: 280,
		CX: 38318, CY: 146154, Half: 1500,
		Mobs: []ZoneMob{
			{
				TemplateID: 20154, Name: "Mandragora Sprout",
				Level: 21, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20223, Name: "Mandragora Sprout",
				Level: 20, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_11-b1", Name: "Dire Wolf W-b1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 29056, CY: 143693, Half: 1650,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_11-a1", Name: "Dire Wolf NW-a1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 29674, CY: 141800, Half: 1650,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_09-b1", Name: "Dire Wolf NW-b1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 31750, CY: 138439, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_09-a1", Name: "Dire Wolf NW-a1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 31809, CY: 136448, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_12", Name: "Dire Wolf NW",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 29092, CY: 138756, Half: 1750,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_19-b1", Name: "Dire Wolf W-b1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 25753, CY: 151312, Half: 1800,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 7, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_19-c1", Name: "Dire Wolf W-c1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 26001, CY: 153749, Half: 1800,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 7, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_08", Name: "Dire Wolf NW",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 30578, CY: 134576, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 3, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_07-b1", Name: "Dire Wolf NW-b1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 28985, CY: 135708, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_19-a1", Name: "Dire Wolf W-a1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 23069, CY: 150668, Half: 1800,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 7, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_07-a1", Name: "Dire Wolf NW-a1",
		Region: regionDion, MinLevel: 23, MaxLevel: 24, MinGear: 290,
		CX: 27018, CY: 135952, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_21s-b1", Name: "Mandragora Sapling W-b1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 40627, CY: 149732, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20156, Name: "Mandragora Blossom",
				Level: 25, Count: 2, Priority: 2,
			},
			{
				TemplateID: 20155, Name: "Mandragora Sapling",
				Level: 23, Count: 3, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_21s-a1", Name: "Mandragora Sapling W-a1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 39230, CY: 149779, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20156, Name: "Mandragora Blossom",
				Level: 25, Count: 2, Priority: 2,
			},
			{
				TemplateID: 20155, Name: "Mandragora Sapling",
				Level: 23, Count: 3, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_20s", Name: "Mandragora Blossom NW",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 39665, CY: 146460, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20156, Name: "Mandragora Blossom",
				Level: 25, Count: 3, Priority: 2,
			},
			{
				TemplateID: 20155, Name: "Mandragora Sapling",
				Level: 23, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_01-c1", Name: "Monster Eye Gazer NW-c1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 33738, CY: 141440, Half: 1650,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 6, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 5, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_20-c1", Name: "Monster Eye Gazer W-c1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 30661, CY: 153266, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 6, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_10-b1", Name: "Monster Eye Gazer NW-b1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 31627, CY: 143023, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 5, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_01-b1", Name: "Monster Eye Gazer NW-b1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 34449, CY: 138839, Half: 1650,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 6, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 5, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_02-b1", Name: "Monster Eye Gazer N-b1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 41380, CY: 134247, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_20-d1", Name: "Monster Eye Gazer W-d1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 30440, CY: 155535, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 6, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_10-a1", Name: "Monster Eye Gazer NW-a1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 31852, CY: 141331, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 5, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_02-a1", Name: "Monster Eye Gazer NW-a1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 39070, CY: 134765, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_01-d1", Name: "Monster Eye Gazer NW-d1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 37011, CY: 135889, Half: 1650,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 6, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 5, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_20-a1", Name: "Monster Eye Gazer W-a1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 28557, CY: 153214, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 6, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_01-a1", Name: "Monster Eye Gazer NW-a1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 34574, CY: 136045, Half: 1650,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 6, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 5, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2022_20-b1", Name: "Monster Eye Gazer W-b1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 28729, CY: 155098, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20266, Name: "Monster Eye Gazer",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 6, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_03-a1", Name: "Kadif Werewolf SW-a1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 1261, CY: 169103, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 6, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 6, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_03-b1", Name: "Kadif Werewolf SW-b1",
		Region: regionDion, MinLevel: 24, MaxLevel: 25, MinGear: 310,
		CX: 1188, CY: 171190, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 6, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 6, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_36", Name: "Specter NE",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 53254, CY: 141444, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20171, Name: "Specter",
				Level: 26, Count: 3, Priority: 1,
			},
			{
				TemplateID: 20156, Name: "Mandragora Blossom",
				Level: 25, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2122_35", Name: "Specter NE",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 55379, CY: 142172, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20171, Name: "Specter",
				Level: 26, Count: 2, Priority: 1,
			},
			{
				TemplateID: 20156, Name: "Mandragora Blossom",
				Level: 25, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_05-g1", Name: "Monster Eye Destroyer SW-g1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 8620, CY: 176095, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 9, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_05-e1", Name: "Monster Eye Destroyer SW-e1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 6276, CY: 173594, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 9, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_05-f1", Name: "Monster Eye Destroyer SW-f1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 6612, CY: 175859, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 9, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_01-a1", Name: "Dire Wolf W-a1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 1336, CY: 165188, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 2, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 5, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_01-b1", Name: "Dire Wolf W-b1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 1314, CY: 167091, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 2, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 4, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 5, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_15s", Name: "Monster Eye Destroyer SW",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 6209, CY: 176810, Half: 1700,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 2, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 2, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_05-c1", Name: "Monster Eye Destroyer SW-c1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 4083, CY: 173484, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 9, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-g1", Name: "Monster Eye Destroyer SW-g1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 6559, CY: 178550, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_05-d1", Name: "Monster Eye Destroyer SW-d1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 4029, CY: 175894, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 9, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_22s-b1", Name: "Giant Mist Leech NW-b1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 7352, CY: 118204, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 3, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_05-a1", Name: "Monster Eye Destroyer SW-a1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 1503, CY: 173762, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 9, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-h1", Name: "Monster Eye Destroyer SW-h1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 5902, CY: 180660, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-d1", Name: "Monster Eye Destroyer SW-d1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 4073, CY: 178731, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_22s-a1", Name: "Giant Mist Leech NW-a1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 7252, CY: 116201, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 3, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 4, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_05-b1", Name: "Monster Eye Destroyer SW-b1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 1450, CY: 175890, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 9, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 9, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-e1", Name: "Monster Eye Destroyer SW-e1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 4053, CY: 181163, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-a1", Name: "Monster Eye Destroyer SW-a1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 1474, CY: 178824, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-f1", Name: "Monster Eye Destroyer SW-f1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 3799, CY: 182810, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-b1", Name: "Monster Eye Destroyer SW-b1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 1456, CY: 181166, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_06-c1", Name: "Monster Eye Destroyer SW-c1",
		Region: regionDion, MinLevel: 25, MaxLevel: 26, MinGear: 340,
		CX: 1373, CY: 183003, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20205, Name: "Dire Wolf",
				Level: 24, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_04-f1", Name: "Giant Mist Leech NW-f1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 16718, CY: 124769, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 10, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 12, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_04-e1", Name: "Giant Mist Leech NW-e1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 16653, CY: 122584, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 10, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 12, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_04-d1", Name: "Giant Mist Leech NW-d1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 14118, CY: 124769, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 10, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 12, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_04-c1", Name: "Giant Mist Leech NW-c1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 14069, CY: 122321, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 10, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 12, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_04-b1", Name: "Giant Mist Leech NW-b1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 11953, CY: 124470, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 10, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 12, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_04-a1", Name: "Giant Mist Leech NW-a1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 11915, CY: 122531, Half: 1400,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 10, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 12, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_03-g1", Name: "Horror Mist Ripper NW-g1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 11246, CY: 120695, Half: 1550,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 7, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_03-f1", Name: "Horror Mist Ripper NW-f1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 9183, CY: 120711, Half: 1550,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 7, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_03-e1", Name: "Horror Mist Ripper NW-e1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 9100, CY: 117897, Half: 1550,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 7, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_03-c1", Name: "Horror Mist Ripper NW-c1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 6914, CY: 119975, Half: 1550,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 7, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_03-d1", Name: "Horror Mist Ripper NW-d1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 8768, CY: 115134, Half: 1550,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 7, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_03-b1", Name: "Horror Mist Ripper NW-b1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 6339, CY: 117871, Half: 1550,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 7, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2021_03-a1", Name: "Horror Mist Ripper NW-a1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 6245, CY: 114980, Half: 1550,
		Mobs: []ZoneMob{
			{
				TemplateID: 20227, Name: "Horror Mist Ripper",
				Level: 27, Count: 8, Priority: 2,
			},
			{
				TemplateID: 20226, Name: "Gray Ant",
				Level: 26, Count: 7, Priority: 1,
			},
			{
				TemplateID: 20225, Name: "Giant Mist Leech",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-e1", Name: "Glass Jaguar SW-e1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 3849, CY: 184905, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-h1", Name: "Glass Jaguar SW-h1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 6262, CY: 189516, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-f1", Name: "Glass Jaguar SW-f1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 4225, CY: 187408, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-a1", Name: "Glass Jaguar SW-a1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 1596, CY: 184898, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-g1", Name: "Glass Jaguar SW-g1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 4136, CY: 189972, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-b1", Name: "Glass Jaguar SW-b1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 1555, CY: 187403, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-c1", Name: "Glass Jaguar SW-c1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 1542, CY: 190109, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
	{
		ID: "dion-2023_07-d1", Name: "Glass Jaguar SW-d1",
		Region: regionDion, MinLevel: 26, MaxLevel: 27, MinGear: 380,
		CX: 1259, CY: 192066, Half: 1450,
		Mobs: []ZoneMob{
			{
				TemplateID: 20250, Name: "Glass Jaguar",
				Level: 27, Count: 9, Priority: 2,
			},
			{
				TemplateID: 20068, Name: "Monster Eye Destroyer",
				Level: 26, Count: 8, Priority: 1,
			},
			{
				TemplateID: 20206, Name: "Kadif Werewolf",
				Level: 25, Count: 8, Priority: 0,
			},
		},
	},
}

// DionHuntingZones returns the hunting grounds of the Dion 20-25 band.
func DionHuntingZones() []HuntingZone {
	zones := make([]HuntingZone, len(dionHuntingZones))
	copy(zones, dionHuntingZones)

	return zones
}
