// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

package hunt

import (
	"math"
	"time"

	"github.com/melg8/swarm/internal/swarm/state"
)

// Multi zone hunting: the hunting grounds of a region are compact
// squares derived from the real spawn polygons of the Mobius spawn
// data (the mobs of a territory spawn at uniformly random points of
// its polygon and their wander stays inside it, so the squares sit
// on the ground the spawn mass actually covers - the registry is
// generated by tools/generate_hunt_zones.py, a big territory splits
// into several squares that rotate into each other), a ladder of
// level bands gates them on the mob band and the equipped gear, and
// the loop rotates between the grounds of one band when a square is
// cleared out faster than the respawn refills it - a rotated-away
// square keeps an empty cooldown so the rotation sweeps forward
// through the band (A to B to C) instead of ping ponging back into
// the square it just left (A to B to A). Every zone carries the full
// mob list of its territory: the engage farms every species inside
// the square (never just one name) with the level sorted priorities
// biasing the pick toward the exp rich mobs of the ground. The death
// regression demotes a band the character died in too often: three
// deaths in one square mean the character does not pull the zone, so
// the ladder caps below that band until the next level change. The
// zone registry is data driven: the elven lands are generated into
// zones_elven.go, the other regions (orcs, dwarves, dark elves,
// humans) join as their own generated lists, and a mage profile
// changes only the gear scoring, never the zone model.

// ZoneMob describes one mob species of a hunting zone: the whole mob
// list of the spawn territory the square covers. The hunt loop farms
// every species of the list (the engage only filters on the level
// safety), the Priority field adds a soft engage preference for the
// exp richer mobs of the ground (see targetPriorityBonus).
type ZoneMob struct {
	// TemplateID is the npc template id of the spawn data.
	TemplateID int32
	// Name is the display name of the mob.
	Name string
	// Level is the mob level of the npc stats.
	Level int32
	// Count is the spawned count of the parent territory.
	Count int32
	// Priority biases the engage toward this species: every point
	// makes the mob read as closer than it stands (soft tie break,
	// distance still dominates far picks).
	Priority int32
}

// HuntingZone describes one hunting ground: the level band of its
// mobs, the gear gate in zone gating points and the square the bot
// leashes itself to (the engage zone of the hunt loop).
type HuntingZone struct {
	// ID is the stable identifier of the zone (region prefixed).
	ID string
	// Name is the display name of the map view.
	Name string
	// Region groups the zones of one territory (elven, orc, ...).
	Region string
	// MinLevel and MaxLevel are the mob level band of the zone.
	MinLevel int32
	MaxLevel int32
	// MinGear is the zone gating points the equipped gear must reach
	// before the bot hunts here (see gear.TotalGearPoints).
	MinGear int32
	// CX, CY and Half describe the hunting square.
	CX   int32
	CY   int32
	Half int32
	// Mobs lists every mob species of the spawn territory the square
	// covers (all of them are farmed inside the square, the
	// priorities bias the engage; empty for hand placed zones).
	Mobs []ZoneMob
}

// regionElven is the region key of the elven lands zone registry.
const regionElven = "elven"

// zoneLevelLead is the level lead the character must hold over the
// top mob of a band before the picker opens it: the fights stay
// winnable when the hunted mobs sit 1-2 levels below the character
// (the observed deaths came from characters that just reached a
// band and engaged mobs above their own level), so every band opens
// at its MaxLevel plus this lead instead of its MinLevel. The starter
// band of the registry is the floor: a character below every band
// hunts it through the starter fallback.
const zoneLevelLead = 1

// zoneSwitchPeriod bounds the automatic zone re-evaluation: the level
// changes and the gear upgrades (the town trips and the auto
// equipment) move the character up the ladder within this period.
const zoneSwitchPeriod = 30 * time.Second

// zoneRotateAfter bounds the patience of a hunter in a cleared-out
// square: the square holds no attackable mob this long after the
// character reached its middle, and the nearest ground of the same
// band is closer than waiting out the respawn of this one (the
// respawn of the elven lands runs at 15-20 s per mob).
const zoneRotateAfter = 10 * time.Second

// zoneEmptyCooldown holds a rotated-away square out of the rotation
// contest: walking back into a square the hunter just cleared only
// finds it still empty (the per mob respawn needs 15-20 s), so the
// rotation sweeps forward through the band - A to B to C - instead
// of ping ponging between the two nearest squares A and B. The
// cooldown spans two emptiness windows plus one respawn cycle.
const zoneEmptyCooldown = 40 * time.Second

// zoneDeathLimit is the death count that demotes a hunting ground: a
// character that died this often in one square does not pull the
// zone, and the band ladder caps below its band (the regression onto
// an easier ground) until the next level change re-opens it.
const zoneDeathLimit = 3

// zoneOverrideSlack is the level slack a manual zone selection keeps
// its override: the automatic picker resumes once the character
// outgrows the band.
const zoneOverrideSlack = 3

// zoneDistance measures the anchor distance between a zone center and
// a world position.
func zoneDistance(zone HuntingZone, x int32, y int32) float64 {
	return math.Hypot(float64(zone.CX-x), float64(zone.CY-y))
}

// zoneBandRank compares the band of two zones for the picker ladder:
// a positive rank means the first zone sits higher (the picker wants
// it), zero means the same band (the tie break rules apply).
func zoneBandRank(zone HuntingZone, other HuntingZone) int {
	if zone.MaxLevel != other.MaxLevel {
		if zone.MaxLevel > other.MaxLevel {
			return 1
		}

		return -1
	}
	if zone.MinLevel != other.MinLevel {
		if zone.MinLevel > other.MinLevel {
			return 1
		}

		return -1
	}

	return 0
}

// sameBand reports whether two zones belong to one rotation group:
// the same mob level window (the rotation never changes difficulty,
// only the square).
func sameBand(zone HuntingZone, other HuntingZone) bool {
	return zone.MinLevel == other.MinLevel &&
		zone.MaxLevel == other.MaxLevel
}

// PickHuntingZone returns the best zone of the list for the character
// level, the gear points and the position: the highest level band
// both gates allow, so the gear gate holds the character back until
// its equipment pays for the stronger mobs. The level gate opens a
// band only above its top mob plus the level lead - the character
// hunts mobs 1-2 levels below itself, never above itself. Among the
// zones of the winning band the current one keeps its post (a
// periodic re-pick never bounces the character between the grounds of
// one band), the nearest one to the character wins an open contest.
// maxMinLevel caps the ladder from above for the death regression
// (zones whose band passes the cap are too hard for now, a negative
// value disables the cap). A character below every band (or under a
// cap that closed the ladder) hunts the starter band through the
// starter fallback contest.
func PickHuntingZone(
	zones []HuntingZone, level int32, gearPoints int32,
	currentID string, fromX int32, fromY int32, maxMinLevel int32,
) (HuntingZone, bool) {
	best := -1
	for index := range zones {
		candidate := zones[index]
		if level < candidate.MaxLevel+zoneLevelLead ||
			gearPoints < candidate.MinGear {
			continue
		}
		if maxMinLevel >= 0 && candidate.MinLevel > maxMinLevel {
			continue
		}
		if best < 0 {
			best = index

			continue
		}
		rank := zoneBandRank(candidate, zones[best])
		if rank > 0 {
			best = index

			continue
		}
		if rank < 0 {
			continue
		}
		// The same band: the current zone keeps its post, otherwise
		// the nearest center wins.
		if candidate.ID == currentID {
			if zones[best].ID != currentID {
				best = index
			}

			continue
		}
		if zones[best].ID == currentID {
			continue
		}
		if zoneDistance(candidate, fromX, fromY) <
			zoneDistance(zones[best], fromX, fromY) {
			best = index
		}
	}
	if best < 0 {
		// Below every band or the cap closed the ladder: the
		// starter band runs its own fallback contest.
		return starterZone(zones, currentID, fromX, fromY)
	}

	return zones[best], true
}

// starterZone resolves the fallback of the picker: the starter band
// (the band of the first zone of the registry) runs its own contest
// when no ladder band opens for the character - a level below every
// band or a death regression that capped the ladder shut. The current
// ground of the starter band keeps its post (the periodic re-pick
// never bounces a sub-band character between the starter squares), an
// open contest takes the nearest ground to the character.
func starterZone(
	zones []HuntingZone, currentID string, fromX int32, fromY int32,
) (HuntingZone, bool) {
	if len(zones) == 0 {
		return noZone, false
	}
	best := 0
	for index := 1; index < len(zones); index++ {
		candidate := zones[index]
		if !sameBand(candidate, zones[0]) {
			continue
		}
		if candidate.ID == currentID {
			if zones[best].ID != currentID {
				best = index
			}

			continue
		}
		if zones[best].ID == currentID {
			continue
		}
		if zoneDistance(candidate, fromX, fromY) <
			zoneDistance(zones[best], fromX, fromY) {
			best = index
		}
	}

	return zones[best], true
}

// containsPoint reports whether the world point lies inside the
// hunting square of the zone.
func (z HuntingZone) containsPoint(x int32, y int32) bool {
	return z.Half > 0 && x >= z.CX-z.Half && x <= z.CX+z.Half &&
		y >= z.CY-z.Half && y <= z.CY+z.Half
}

// noZone is the zero zone of the not-found returns (exhaustruct
// wants the plain var instead of a partial literal).
var noZone HuntingZone

// zoneByID resolves a zone of the registry by its id.
func (l *Loop) zoneByID(id string) (HuntingZone, bool) {
	if id == "" {
		return noZone, false
	}
	for index := range l.zones {
		if l.zones[index].ID == id {
			return l.zones[index], true
		}
	}

	return noZone, false
}

// SetHuntingZones installs the zone registry of the deployment: the
// loop picks the zone for the character state on the next tick and
// re-evaluates it as the level and the gear grow. Without a registry
// the loop hunts with the plain SetHuntingZone square (or without a
// zone at all).
func (l *Loop) SetHuntingZones(zones []HuntingZone) {
	l.zones = zones
	l.zoneOverride = -1
	l.zonePickedID = ""
	l.zoneCheckAt = time.Time{}
	l.zoneDeaths = nil
	l.zoneDeathCap = -1
	l.zoneDeathLevel = 0
	l.zoneEmptySince = time.Time{}
	l.zoneEmptyUntil = nil
	l.publishZoneView()
}

// SetHuntingZoneRegion installs the registry of one region by name
// ("elven"): the map of the future deployments.
func (l *Loop) SetHuntingZoneRegion(region string) {
	switch region {
	case regionElven, "":
		l.SetHuntingZones(ElvenHuntingZones())
	default:
		l.logger.Printf("Hunt: no zone registry for region %q, hunting "+
			"without zones", region)
	}
}

// userZoneSelect applies the manual zone selection of the web UI: the
// index refers to the zone registry order. The selection overrides
// the automatic picker until the character outgrows the band.
func (l *Loop) userZoneSelect(index int32) {
	if len(l.zones) == 0 {
		return
	}
	if index < 0 || int(index) >= len(l.zones) {
		l.logger.Printf("Hunt: zone index %d out of range", index)

		return
	}
	zone := l.zones[index]
	l.zoneOverride = int(index)
	l.logger.Printf("Hunt: user selected the hunting zone %s", zone.Name)
	l.stopForZoneSwitch()
	l.applyHuntingZone(zone)
}

// stopForZoneSwitch halts the walks the manual zone selection makes
// pointless: a manual move, a town trip walk to the trader or back
// and a zone return leg all aimed at the old square. The server
// keeps a walk running until the next move request replaces its
// destination, so one walk request to the current spot stops it. The
// selling stop (the character stands at the merchant) keeps running
// - its return leg re-targets the new zone on its own - and the
// deleveling refuses the stop like it refuses every movement
// command.
func (l *Loop) stopForZoneSwitch() {
	if l.phase == phaseDelevel {
		return
	}
	if l.phase == phaseUser && l.userKind == state.CommandMove {
		l.resumeAuto()
	}
	if l.phase == phaseTownWalk || l.phase == phaseTownReturn {
		l.resetTownTrip()
		l.zoneReturn = false
		l.zoneFails = 0
	}
	if x, y, z, ok := l.tracker.SelfPosition(); ok &&
		l.tracker.SelfWalking() {
		if err := l.game.WalkTo(x, y, z); err != nil {
			l.logger.Printf("Hunt: zone switch stop walk failed: %v", err)
		}
	}
}

// maybeSwitchZone re-evaluates the automatic zone pick: a level gain
// or a gear upgrade moves the character up the ladder, a cleared-out
// square rotates to the next ground of its band, and the death
// bookkeeping resets when the level changes. The ladder re-pick only
// happens between the fights (no target, nobody attacks), so a
// running fight always finishes in the old square.
func (l *Loop) maybeSwitchZone() {
	if len(l.zones) == 0 {
		return
	}
	now := time.Now()
	l.resetZoneDeathState()
	if l.zoneOverride < 0 {
		l.maybeRotateEmptyZone(now)
	}
	if l.zonePickedID != "" && now.Sub(l.zoneCheckAt) < zoneSwitchPeriod {
		return
	}
	l.zoneCheckAt = now
	level := l.tracker.SelfLevel()
	if l.zoneOverride >= 0 {
		zone := l.zones[l.zoneOverride]
		if level <= zone.MaxLevel+zoneOverrideSlack {
			return
		}
		l.zoneOverride = -1
		l.logger.Printf("Hunt: outgrew the manual zone %s, resuming the "+
			"automatic picker", zone.Name)
	}
	fromX, fromY := l.selfZoneAnchor()
	zone, ok := PickHuntingZone(l.zones, level, l.gearPoints(),
		l.zonePickedID, fromX, fromY, l.zoneDeathCap)
	if !ok || zone.ID == l.zonePickedID {
		return
	}
	l.applyHuntingZone(zone)
	l.logger.Printf("Hunt: level %d with gear %d: hunting %s (levels "+
		"%d-%d)", level, l.gearPoints(), zone.Name, zone.MinLevel,
		zone.MaxLevel)
}

// selfZoneAnchor returns the anchor of the nearest zone tie break:
// the character position when known, the center of the current
// square otherwise (the zone of the last hunt is a better guess of
// the whereabouts than the origin of the world).
func (l *Loop) selfZoneAnchor() (int32, int32) {
	if x, y, _, ok := l.tracker.SelfPosition(); ok {
		return x, y
	}
	if l.zoneHalf > 0 {
		return l.zoneCX, l.zoneCY
	}

	return 0, 0
}

// maybeRotateEmptyZone rotates the hunting ground of a cleared-out
// square: the pack of a small square dies out faster than the respawn
// refills it when the kills outpace the spawner, so a hunter that
// stands in the middle of a mob-less square for the rotate window
// moves on to the nearest ground of the same band that is not
// cooling down from an earlier rotation. The emptiness reading
// only counts the mobs the character can actually fight (the level
// filter of the engage - a square whose survivors all sit above the
// max target level is as good as empty for this hunter) and only
// while the character stands central (the tracker only knows the
// mobs the server showed it, and the patrol walk brings the
// character to the middle first); running fights, resting walks and
// town trips reset the timer - a rotation never abandons any of
// them.
// The linear guard chain is the emptiness protocol itself: every
// guard either resets or holds the empty timer, and splitting it
// would scatter that contract over helpers.
func (l *Loop) maybeRotateEmptyZone(now time.Time) { //nolint:cyclop
	zone := l.zone()
	if zone == nil || l.zonePickedID == "" {
		l.zoneEmptySince = time.Time{}

		return
	}
	if l.phase != phaseEngage || l.target != 0 || l.tripActive() ||
		l.tracker.SelfUnderAttack() || l.tracker.SelfSitting() ||
		!l.inZoneSelf() {
		l.zoneEmptySince = time.Time{}

		return
	}
	selfX, selfY, _, ok := l.tracker.SelfPosition()
	if !ok {
		return
	}
	if math.Hypot(float64(zone.CX-selfX), float64(zone.CY-selfY)) >
		float64(zone.Half) {
		// The patrol walk has not brought the character to the middle
		// yet: the emptiness reading of the far corners is not
		// trustworthy.
		l.zoneEmptySince = time.Time{}

		return
	}
	if l.tracker.ZoneHasAttackableBelow(zone, l.maxTargetLevel()) {
		l.zoneEmptySince = time.Time{}

		return
	}
	if l.zoneEmptySince.IsZero() {
		l.zoneEmptySince = now

		return
	}
	if now.Sub(l.zoneEmptySince) < zoneRotateAfter {
		return
	}
	// The window is up: re-arm the timer either way, so a square
	// without a rotation target waits out another full window instead
	// of spinning the check every tick.
	l.zoneEmptySince = now
	next, ok := l.rotationZone(selfX, selfY, now)
	if !ok {
		return
	}
	current, currentOK := l.zoneByID(l.zonePickedID)
	if currentOK {
		// The rotated-away square keeps its cooldown: the next
		// rotations of the band sweep forward past it instead of
		// walking straight back into the cleared ground.
		l.markZoneEmpty(current.ID, now)
	}
	l.applyHuntingZone(next)
	l.zoneCheckAt = now
	if currentOK {
		l.logger.Printf("Hunt: %s is cleared out, rotating to %s",
			current.Name, next.Name)

		return
	}
	l.logger.Printf("Hunt: the zone is cleared out, rotating to %s",
		next.Name)
}

// markZoneEmpty starts the empty cooldown of a rotated-away zone and
// prunes the expired entries of the bookkeeping map on the way (the
// registry holds a few hundred squares, the map must not grow
// forever).
func (l *Loop) markZoneEmpty(id string, now time.Time) {
	if l.zoneEmptyUntil == nil {
		l.zoneEmptyUntil = make(map[string]time.Time)
	}
	for zoneID, until := range l.zoneEmptyUntil {
		if now.After(until) {
			delete(l.zoneEmptyUntil, zoneID)
		}
	}
	l.zoneEmptyUntil[id] = now.Add(zoneEmptyCooldown)
}

// zoneCoolingDown reports whether the zone sits in its post-rotation
// empty cooldown at the given time.
func (l *Loop) zoneCoolingDown(id string, now time.Time) bool {
	until, ok := l.zoneEmptyUntil[id]

	return ok && now.Before(until)
}

// rotationZone picks the rotation target of a cleared-out square: the
// nearest zone of the same band (the same mob level window, so the
// rotation never changes the difficulty), never the current one and
// never a square that still cools down from an earlier rotation -
// the sweep moves forward through the band instead of ping ponging
// back and forth between the two nearest squares. The death cap
// holds even here: a demoted band is done for now.
func (l *Loop) rotationZone(
	selfX int32, selfY int32, now time.Time,
) (HuntingZone, bool) {
	current, ok := l.zoneByID(l.zonePickedID)
	if !ok {
		return noZone, false
	}
	best := -1
	bestDist := math.MaxFloat64
	for index := range l.zones {
		candidate := l.zones[index]
		if candidate.ID == current.ID ||
			!sameBand(candidate, current) {
			continue
		}
		if l.zoneDeathCap >= 0 && candidate.MinLevel > l.zoneDeathCap {
			continue
		}
		if l.zoneCoolingDown(candidate.ID, now) {
			continue
		}
		if dist := zoneDistance(candidate, selfX, selfY); dist < bestDist {
			best = index
			bestDist = dist
		}
	}
	if best < 0 {
		return noZone, false
	}

	return l.zones[best], true
}

// noteZoneDeath counts a hunting death against the zone the death
// happened in: the square that contains the death spot first (an
// emergency logout death lands on a fresh session before any zone
// pick - the death spot is the only truthful attribution), the picked
// zone of the loop as the fallback (a flight that ended between the
// squares still belongs to the ground it fled from). Past the death
// limit the zone outguns the character, the band ladder caps below
// the zone band (the regression onto an easier ground) and the next
// tick re-picks with the cap. The counting happens in
// recoverFromDeath; the deleveling deaths are the point of that phase
// and never count.
func (l *Loop) noteZoneDeath() {
	zone, ok := l.deathZone()
	if !ok {
		return
	}
	if l.zoneDeaths == nil {
		l.zoneDeaths = make(map[string]int32)
	}
	l.zoneDeaths[zone.ID]++
	deaths := l.zoneDeaths[zone.ID]
	if deaths < zoneDeathLimit {
		l.logger.Printf("Hunt: death %d of %d in %s",
			deaths, zoneDeathLimit, zone.Name)
		l.publishZoneView()

		return
	}
	if l.zoneDeathCap < 0 || zone.MinLevel-1 < l.zoneDeathCap {
		l.zoneDeathCap = zone.MinLevel - 1
	}
	// A manual zone selection dies with the demotion: the operator
	// picked the ground, but the character keeps dying in it - the
	// regression takes over instead of walking the corpse back into
	// the same blows.
	if l.zoneOverride >= 0 {
		l.zoneOverride = -1
	}
	// Force the ladder re-pick on the next living tick: the gate of
	// maybeSwitchZone passes with a zero evaluation time.
	l.zoneCheckAt = time.Time{}
	l.zoneEmptySince = time.Time{}
	l.publishZoneView()
	l.logger.Printf("Hunt: %d deaths in %s, the zone outguns the "+
		"character: regressing to an easier band (capped below level "+
		"%d) until the level grows", deaths, zone.Name, zone.MinLevel)
}

// deathZone resolves the zone a death counts against: the square
// that contains the death spot, the picked zone when the spot lies
// between the squares (a flight that died outside every ground).
func (l *Loop) deathZone() (HuntingZone, bool) {
	if x, y, _, ok := l.tracker.SelfPosition(); ok {
		for index := range l.zones {
			if l.zones[index].containsPoint(x, y) {
				return l.zones[index], true
			}
		}
	}

	return l.zoneByID(l.zonePickedID)
}

// resetZoneDeathState clears the zone death bookkeeping when the
// character level changes (a level up the ladder or a level down the
// deleveling): the level is the measure of what the character pulls,
// so every level change re-opens the demoted bands for a retry.
func (l *Loop) resetZoneDeathState() {
	level := l.tracker.SelfLevel()
	if level == 0 || level == l.zoneDeathLevel {
		return
	}
	first := l.zoneDeathLevel == 0
	l.zoneDeathLevel = level
	if len(l.zoneDeaths) == 0 && l.zoneDeathCap < 0 {
		return
	}
	l.zoneDeaths = nil
	l.zoneDeathCap = -1
	l.publishZoneView()
	if !first {
		l.logger.Printf("Hunt: level %d: the zone death bookkeeping "+
			"resets", level)
	}
}

// applyHuntingZone switches the hunting square of the loop and the
// tracker and publishes the zone view of the map. The remembered
// farm spot belongs to the previous square: the switch drops it, so
// the returns aim at the new center until the hunt remembers a
// fresh spot inside it. The rotation timer starts over: the new
// square gets its own empty window before any rotation away from it.
// The mob list of the ground becomes the engage bias: every species
// of the square stays attackable, the priorities tilt the pick toward
// the exp rich mobs.
func (l *Loop) applyHuntingZone(zone HuntingZone) {
	l.zonePickedID = zone.ID
	l.zoneCX, l.zoneCY, l.zoneHalf = zone.CX, zone.CY, zone.Half
	l.farmX, l.farmY, l.farmZ = 0, 0, 0
	l.zoneEmptySince = time.Time{}
	l.zoneMobPriority = zoneMobPriority(zone)
	l.tracker.SetHuntingZone(zone.CX, zone.CY, zone.Half)
	l.publishZoneView()
}

// zoneMobPriority builds the template id to priority map of a zone
// mob list: nil when the list carries no priorities (the plain
// nearest-first pick of the zones without mob data).
func zoneMobPriority(zone HuntingZone) map[int32]int32 {
	var priorities map[int32]int32
	for index := range zone.Mobs {
		mob := &zone.Mobs[index]
		if mob.Priority <= 0 {
			continue
		}
		if priorities == nil {
			priorities = make(map[int32]int32, len(zone.Mobs))
		}
		priorities[mob.TemplateID] = mob.Priority
	}

	return priorities
}

// publishZoneView pushes the zone registry with the active marker to
// the tracker snapshot: the map draws every zone and highlights the
// one the bot hunts in (or walks to), the death counts and the
// demoted bands of the regression travel along for the zone panel.
func (l *Loop) publishZoneView() {
	if l.tracker == nil {
		return
	}
	views := make([]state.ZoneView, 0, len(l.zones))
	for _, zone := range l.zones {
		views = append(views, state.ZoneView{
			ID:       zone.ID,
			Name:     zone.Name,
			Region:   zone.Region,
			MinLevel: zone.MinLevel,
			MaxLevel: zone.MaxLevel,
			MinGear:  zone.MinGear,
			CX:       zone.CX,
			CY:       zone.CY,
			Half:     zone.Half,
			Active:   zone.ID == l.zonePickedID,
			Deaths:   l.zoneDeaths[zone.ID],
			Demoted:  l.zoneDeathCap >= 0 && zone.MinLevel > l.zoneDeathCap,
		})
	}
	l.tracker.SetHuntingZones(views)
}
