// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

package logfmt

import (
    "os"
    "path/filepath"
    "testing"

    "github.com/stretchr/testify/require"
)

// writeSource lays one sample source file into a fresh tree and
// returns the tree root.
func writeSource(t *testing.T, name, code string) string {
    t.Helper()
    root := t.TempDir()
    path := filepath.Join(root, name)
    require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
    require.NoError(t, os.WriteFile(path, []byte(code), 0o600))

    return root
}

func TestScanTreeFindsTheViolations(t *testing.T) {
    root := writeSource(t, "pkg/sample.go", `package pkg

import "log"

var logger = log.New(nil, "", 0)

func sample() {
    log.Println("lowercase start without a tag") // capital
    log.Println("ends with a period.")           // period
    log.Printf("%d verbs are fine", 1)
    log.Printf("login#%d: the proxy tag is fine", 3)
    log.Println("Hunt audit: capital fine")
    log.Println("Hunt audit: capital fine.")   // period
    logger.Printf("field logger lowercase")    // capital
    log.Println("wrapped " + "concat period.") // period
    dynamic := "a variable message"
    log.Println(dynamic)
}
`)
    violations, err := ScanTree(root)
    require.NoError(t, err)
    rules := map[string]int{}
    for _, violation := range violations {
        require.Equal(t, filepath.Join(root, "pkg", "sample.go"),
            violation.File)
        rules[violation.Rule]++
    }
    require.Equal(t, 4, rules["capital"])
    require.Equal(t, 3, rules["period"])
}

func TestScanTreeSkipsGeneratedAndTests(t *testing.T) {
    root := writeSource(t, "pkg/bad.go", `// Code generated by gen. DO NOT EDIT.

package pkg

import "log"

func gen() {
    log.Println("lowercase generated noise.")
}
`)
    root2 := writeSource(t, "pkg/bad_test.go", `package pkg

import "testing"

func TestX(t *testing.T) {
    t.Log("test chatter stays out of scope.")
}
`)
    require.NoError(t, os.WriteFile(filepath.Join(root2, "pkg",
        "bad_test.go"), []byte(`package pkg

import "log"

func helper() {
    log.Println("test file lowercase.")
}
`), 0o600))
    for _, dir := range []string{root, root2} {
        violations, err := ScanTree(dir)
        require.NoError(t, err)
        require.Empty(t, violations)
    }
}

func TestStringLiteralsWalksTheConcatChain(t *testing.T) {
    require.Nil(t, stringLiterals(nil))
}

// TestRepoLogConventions pins the AGENTS.md logging conventions at
// every production log call site of the module: the scan of the whole
// tree must come back empty. A new violation means the message needs
// a capital first letter (a lowercase component tag like
// "login#%d:" or "hunt audit:" is a valid start too) and no trailing
// period - fix the message, not the checker; the checker exists so
// the convention survives without a reviewer in the loop.
func TestRepoLogConventions(t *testing.T) {
    violations, err := ScanTree("../..")
    require.NoError(t, err)
    for _, violation := range violations {
        t.Errorf("%s:%d %s: %q",
            violation.File, violation.Line,
            violation.Rule, violation.Message)
    }
}
