// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

package gear

// dionTownTaxRate is the buy tax markup of the Town of Dion
// (MerchantPriceConfig.xml priceConfig id="8", baseTax="20", the
// castle tax is 0 on the local test server so the total is the base
// tax). The formula matches the elven village 0.15 of the elven
// catalog: price = baseItemPrice * (1 + taxRate).
const dionTownTaxRate = 0.20

// The packet template ids (the display ids of the NpcInfo packets) of
// the Dion merchants the band gear shopping trip targets, from
// docs/band_20_25_survey.md. The buylist ids are the file names of
// dist/game/data/buylists/; the npcdata.npcBuyLists map (generated by
// tools/generate_shop_catalogs.sh) resolves them at runtime.
const (
	dionWeaponMerchant  = int32(7060) // Sabrin
	dionArmorMerchant   = int32(7061) // Casey
	dionJewelMerchant   = int32(7062) // Sonia
	dionGroceryMerchant = int32(7063) // Lara
)

// DionCatalog returns the gear catalog of the Town of Dion merchants
// the 20-25 band shopping trip targets: Sabrin (weapons), Casey
// (armor), Sonia (jewels + spellbooks) and Lara (grocery), at the 20
// percent Dion buy tax. The buylist ids are the file names of
// dist/game/data/buylists/ (3006000-3006300 of the survey); the
// npcdata.BuyListsOfNPC call the hunt shopping loop makes resolves
// them to the item ids at runtime.
//
// The catalog is the M3 counterpart of the elven village catalog: the
// elven village serves the 1-19 band (the NG-to-D transition gear of
// the survey), Dion serves the 20-25 band (the D-grade gear the
// survey bands table names). The hunt shopping loop wires the catalog
// selection to the current town (the follow-up of T-010, out of the
// gear package scope).
func DionCatalog() Catalog {
	return Catalog{Shops: []Shop{
		{
			MerchantTemplateID: dionWeaponMerchant,
			TaxRate:            dionTownTaxRate,
			Lists:              []int32{3006000, 3006001},
		},
		{
			MerchantTemplateID: dionArmorMerchant,
			TaxRate:            dionTownTaxRate,
			Lists:              []int32{3006100, 3006101},
		},
		{
			MerchantTemplateID: dionJewelMerchant,
			TaxRate:            dionTownTaxRate,
			Lists:              []int32{3006200, 3006201},
		},
		{
			MerchantTemplateID: dionGroceryMerchant,
			TaxRate:            dionTownTaxRate,
			Lists:              []int32{3006300},
		},
	}}
}
