// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

// Code generated by tools/generate_merchant_spawns.sh. DO NOT EDIT.
package npcdata

import "sort"

// MerchantSpawn is one world spawn of a shop merchant: the spawn
// position and the facing heading of the Mobius C1 spawn data,
// keyed by the packet template id (the display id of the NpcInfo
// packets, the key of the generated buylist catalogs).
type MerchantSpawn struct {
    Name    string
    X       int32
    Y       int32
    Z       int32
    Heading int32
}

// merchantSpawns holds every world spawn of every npc the
// generated buylist catalogs know (one spawn per display id in the
// C1 spawn data). The counterprobe tool derives the customer stand
// points from it and the trip machinery resolves the approach
// point of a merchant id through it.
var merchantSpawns = map[int32]MerchantSpawn{
    7001:  {Name: "Lector", X: -86385, Y: 243267, Z: -3717, Heading: 52000},
    7002:  {Name: "Jackson", X: -86733, Y: 242918, Z: -3720, Heading: 61440},
    7003:  {Name: "Silvia", X: -83789, Y: 240799, Z: -3717, Heading: 32768},
    7004:  {Name: "Katerina", X: -84204, Y: 240403, Z: -3720, Heading: 14000},
    7047:  {Name: "Firon", X: -97131, Y: 258946, Z: -3616, Heading: 0},
    7060:  {Name: "Sabrin", X: 17999, Y: 144484, Z: -3046, Heading: 6000},
    7061:  {Name: "Casey", X: 17948, Y: 144560, Z: -3046, Heading: 6000},
    7062:  {Name: "Sonia", X: 19313, Y: 146229, Z: -3069, Heading: 49152},
    7063:  {Name: "Lara", X: 19223, Y: 146228, Z: -3069, Heading: 49152},
    7078:  {Name: "Pano", X: 16970, Y: 170391, Z: -3496, Heading: 61440},
    7081:  {Name: "Helvetia", X: 80518, Y: 147922, Z: -3506, Heading: 32768},
    7082:  {Name: "Denkus", X: 80518, Y: 147873, Z: -3506, Heading: 32768},
    7084:  {Name: "Graham", X: 79747, Y: 146492, Z: -3518, Heading: 16384},
    7085:  {Name: "Stanford", X: 79801, Y: 146493, Z: -3518, Heading: 16384},
    7087:  {Name: "Peta", X: 79711, Y: 150788, Z: -3520, Heading: 49152},
    7088:  {Name: "Radia", X: 79654, Y: 150788, Z: -3520, Heading: 49152},
    7090:  {Name: "Sandra", X: 80511, Y: 149183, Z: -3508, Heading: 32768},
    7091:  {Name: "Ellie", X: 80510, Y: 149250, Z: -3508, Heading: 32768},
    7094:  {Name: "Gentler", X: 83317, Y: 150821, Z: -3514, Heading: 32768},
    7135:  {Name: "Iria", X: 10761, Y: 17970, Z: -4554, Heading: 49152},
    7136:  {Name: "Payne", X: 10823, Y: 18013, Z: -4554, Heading: 61440},
    7137:  {Name: "Vollodos", X: 11951, Y: 15661, Z: -4554, Heading: 28672},
    7138:  {Name: "Minaless", X: 12009, Y: 15704, Z: -4554, Heading: 16384},
    7147:  {Name: "Unoren", X: 44667, Y: 46896, Z: -2982, Heading: 31000},
    7148:  {Name: "Ariel", X: 44683, Y: 46952, Z: -2981, Heading: 28672},
    7149:  {Name: "Creamees", X: 42700, Y: 50057, Z: -2984, Heading: 14500},
    7150:  {Name: "Herbiel", X: 42766, Y: 50037, Z: -2984, Heading: 11500},
    7163:  {Name: "Rex", X: 85982, Y: 16193, Z: -4271, Heading: 32768},
    7164:  {Name: "Ian", X: 85655, Y: 15638, Z: -4271, Heading: 22000},
    7165:  {Name: "Ralford", X: 85004, Y: 16760, Z: -4271, Heading: 54000},
    7166:  {Name: "Wesley", X: 85655, Y: 16767, Z: -4271, Heading: 43500},
    7178:  {Name: "Zenkin", X: 79111, Y: 53657, Z: -1548, Heading: 0},
    7179:  {Name: "Raudia", X: 79112, Y: 53602, Z: -1548, Heading: 0},
    7180:  {Name: "Sara", X: 79451, Y: 54973, Z: -1541, Heading: 0},
    7181:  {Name: "Galibredo", X: 79451, Y: 54877, Z: -1542, Heading: 0},
    7207:  {Name: "Arodin", X: -80343, Y: 154897, Z: -3162, Heading: 16384},
    7208:  {Name: "Damion", X: -80935, Y: 155526, Z: -3162, Heading: 0},
    7230:  {Name: "Edroc", X: 115116, Y: 75923, Z: -2580, Heading: 59000},
    7231:  {Name: "Garette", X: 116109, Y: 75022, Z: -2583, Heading: 57344},
    7253:  {Name: "Simplon", X: -15132, Y: 123282, Z: -3107, Heading: 12288},
    7254:  {Name: "Harmony", X: -14934, Y: 124468, Z: -3114, Heading: 61440},
    7294:  {Name: "Varan", X: -14933, Y: 124540, Z: -3115, Heading: 4096},
    7301:  {Name: "Hally", X: 116646, Y: 74820, Z: -2581, Heading: 28672},
    7313:  {Name: "Asha", X: -81266, Y: 152076, Z: -3125, Heading: 32768},
    7314:  {Name: "Nestle", X: -80108, Y: 153307, Z: -3162, Heading: 0},
    7315:  {Name: "Poesia", X: -79405, Y: 153963, Z: -3160, Heading: 49152},
    7321:  {Name: "Sydnia", X: -15238, Y: 123282, Z: -3107, Heading: 20480},
    7387:  {Name: "Clancy", X: -91792, Y: 149968, Z: -3629, Heading: 0},
    7420:  {Name: "Tyra", X: -61717, Y: 75401, Z: -3352, Heading: 58500},
    7436:  {Name: "Sarien", X: -16832, Y: 210256, Z: -3661, Heading: 55000},
    7437:  {Name: "Rolento", X: -17312, Y: 208976, Z: -3661, Heading: 3000},
    7516:  {Name: "Reep", X: 115741, Y: -181645, Z: -1320, Heading: 8192},
    7517:  {Name: "Shari", X: 116192, Y: -181072, Z: -1336, Heading: 40960},
    7518:  {Name: "Garita", X: 115900, Y: -177316, Z: -880, Heading: 50000},
    7519:  {Name: "Mion", X: 116268, Y: -177524, Z: -880, Heading: 32768},
    7558:  {Name: "Jakal", X: -44416, Y: -111486, Z: -216, Heading: 57600},
    7559:  {Name: "Kunai", X: -43905, Y: -111824, Z: -216, Heading: 28672},
    7560:  {Name: "Uska", X: -43910, Y: -115518, Z: -194, Heading: 39000},
    7561:  {Name: "Papuma", X: -43950, Y: -115457, Z: -194, Heading: 39000},
    7684:  {Name: "Viktor", X: 115310, Y: 75447, Z: -2581, Heading: 12288},
    7731:  {Name: "Martin", X: -84624, Y: 150832, Z: -3129, Heading: 0},
    7827:  {Name: "Lundy", X: -13908, Y: 123322, Z: -3116, Heading: 16384},
    7828:  {Name: "Waters", X: 19276, Y: 142864, Z: -3032, Heading: 32768},
    7829:  {Name: "Cooper", X: 81100, Y: 145840, Z: -3531, Heading: 32768},
    7830:  {Name: "Joey", X: 81992, Y: 54048, Z: -1494, Heading: 0},
    7831:  {Name: "Nelson", X: 117432, Y: 76044, Z: -2716, Heading: 15000},
    7834:  {Name: "Cema", X: 105792, Y: 114290, Z: -3136, Heading: 49000},
    7837:  {Name: "Woodrow", X: 146787, Y: 26255, Z: -2189, Heading: 32768},
    7838:  {Name: "Woodley", X: 146046, Y: 27293, Z: -2189, Heading: 49152},
    7839:  {Name: "Holly", X: 146054, Y: 27988, Z: -2250, Heading: 16384},
    7840:  {Name: "Lorenzo", X: 146893, Y: 28982, Z: -2250, Heading: 32768},
    7841:  {Name: "Carson", X: 148860, Y: 27959, Z: -2253, Heading: 16384},
    7842:  {Name: "Alexis", X: 148142, Y: 28986, Z: -2253, Heading: 0},
    7869:  {Name: "Lemper", X: 145168, Y: 30432, Z: -2461, Heading: 57344},
    7879:  {Name: "Felton", X: 48564, Y: 186548, Z: -3445, Heading: 42000},
    12316: {Name: "Greenspan", X: -17876, Y: 108944, Z: -2485, Heading: 16384},
    12317: {Name: "Mercenary Manager Sanford", X: 21836, Y: 160806, Z: -2679, Heading: 49152},
    12318: {Name: "Morrison", X: 83056, Y: 37425, Z: -2280, Heading: 32768},
    12319: {Name: "Arvid", X: 116984, Y: 145278, Z: -2555, Heading: 32768},
    12320: {Name: "Eldon", X: 147952, Y: 3742, Z: -307, Heading: 32768},
    12844: {Name: "Tamutak", X: 43129, Y: 108841, Z: -1984, Heading: 0},
    12846: {Name: "Ruben", X: -79357, Y: 150232, Z: -3037, Heading: 40000},
    12847: {Name: "Horner", X: -79587, Y: 151436, Z: -3041, Heading: 8192},
    12848: {Name: "Bremmer", X: -84596, Y: 152253, Z: -3125, Heading: 53248},
    12849: {Name: "Kalis", X: -84276, Y: 153321, Z: -3161, Heading: 0},
    12850: {Name: "Winker", X: -84282, Y: 155597, Z: -3160, Heading: 48512},
    12851: {Name: "Black", X: -16159, Y: 123728, Z: -3102, Heading: 53248},
    12852: {Name: "Dillon", X: -12866, Y: 124166, Z: -3096, Heading: 57344},
    12853: {Name: "Boyer", X: -14852, Y: 125413, Z: -3130, Heading: 16384},
    12854: {Name: "Tim", X: -13745, Y: 125573, Z: -3129, Heading: 32768},
    12861: {Name: "Seth", X: 19996, Y: 146216, Z: -3111, Heading: 57344},
    12862: {Name: "Ron", X: 17621, Y: 144920, Z: -3037, Heading: 12288},
    12863: {Name: "Flynn", X: 18634, Y: 143342, Z: -3010, Heading: 64500},
}

// MerchantSpawnOf resolves the world spawn of the merchant packet
// template id. It reports false when the npc sells nothing through
// the catalogs or the spawn data spawns it nowhere.
func MerchantSpawnOf(templateID int32) (MerchantSpawn, bool) {
    spawn, ok := merchantSpawns[templateID]

    return spawn, ok
}

// MerchantSpawnCount returns the number of the world merchant
// spawns the table carries.
func MerchantSpawnCount() int {
    return len(merchantSpawns)
}

// MerchantTemplateIDs returns the packet template ids of every
// world merchant spawn, sorted (the enumeration key of the
// counterprobe stand derivation).
func MerchantTemplateIDs() []int32 {
    ids := make([]int32, 0, len(merchantSpawns))
    for id := range merchantSpawns {
        ids = append(ids, id)
    }
    sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })

    return ids
}
