// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

// Code generated by tools/generate_skill_teachers.sh. DO NOT EDIT.

package npcdata

// skillTeachers maps the class id to the teachers of the
// class that stand in the deployment village (the Elven
// Village spawns): the packet display id the NpcInfo packet
// carries, the name and the spawn point. TeachersOfClass in
// skills.go answers the lookup.
var skillTeachers = map[int32][]TeacherNPC{
	18: {
		{TemplateID: 7155, Name: "Ellenia", X: 45725, Y: 52105, Z: -2792},
		{TemplateID: 7156, Name: "Cobendell", X: 44823, Y: 52414, Z: -2792},
	},
	19: {
		{TemplateID: 7155, Name: "Ellenia", X: 45725, Y: 52105, Z: -2792},
		{TemplateID: 7156, Name: "Cobendell", X: 44823, Y: 52414, Z: -2792},
	},
	20: {
		{TemplateID: 7155, Name: "Ellenia", X: 45725, Y: 52105, Z: -2792},
		{TemplateID: 7156, Name: "Cobendell", X: 44823, Y: 52414, Z: -2792},
	},
	21: {
		{TemplateID: 7155, Name: "Ellenia", X: 45725, Y: 52105, Z: -2792},
		{TemplateID: 7156, Name: "Cobendell", X: 44823, Y: 52414, Z: -2792},
	},
	22: {
		{TemplateID: 7155, Name: "Ellenia", X: 45725, Y: 52105, Z: -2792},
		{TemplateID: 7156, Name: "Cobendell", X: 44823, Y: 52414, Z: -2792},
	},
	23: {
		{TemplateID: 7155, Name: "Ellenia", X: 45725, Y: 52105, Z: -2792},
		{TemplateID: 7156, Name: "Cobendell", X: 44823, Y: 52414, Z: -2792},
	},
	24: {
		{TemplateID: 7155, Name: "Ellenia", X: 45725, Y: 52105, Z: -2792},
		{TemplateID: 7156, Name: "Cobendell", X: 44823, Y: 52414, Z: -2792},
	},
	25: {
		{TemplateID: 7157, Name: "Greenis", X: 45000, Y: 52101, Z: -2792},
		{TemplateID: 7158, Name: "Esrandell", X: 45919, Y: 52414, Z: -2792},
	},
	26: {
		{TemplateID: 7157, Name: "Greenis", X: 45000, Y: 52101, Z: -2792},
	},
	27: {
		{TemplateID: 7157, Name: "Greenis", X: 45000, Y: 52101, Z: -2792},
	},
	28: {
		{TemplateID: 7157, Name: "Greenis", X: 45000, Y: 52101, Z: -2792},
	},
	29: {
		{TemplateID: 7158, Name: "Esrandell", X: 45919, Y: 52414, Z: -2792},
	},
	30: {
		{TemplateID: 7158, Name: "Esrandell", X: 45919, Y: 52414, Z: -2792},
	},
}
