#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
# SPDX-License-Identifier: MIT
#
# Regenerate the system message dictionary of the bot from the Mobius C1
# server sources. SystemMessage (0x7A) packets carry only a message id
# plus parameters; the id maps to the client side text through the
# @ClientString annotations of SystemMessageId.java. The generated map
# lets the bot log human readable loot and status messages ("You have
# earned 25 adena") instead of raw packet ids.
#
# Usage: tools/generate_system_messages.sh [path/to/L2J_Mobius_C1_HarbingersOfWar]
# Output: internal/swarm/npcdata/system_messages.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOBIUS_C1="${1:-$(dirname "${SWARM_ROOT}")/l2j_mobius/L2J_Mobius_C1_HarbingersOfWar}"
OUT="${SCRIPT_DIR}/../internal/swarm/npcdata/system_messages.go"

SOURCE="${MOBIUS_C1}/java/org/l2jmobius/gameserver/network/SystemMessageId.java"
[ -f "${SOURCE}" ] || {
    echo "Error SystemMessageId.java not found at ${SOURCE}"
    echo "Usage: $0 [path/to/L2J_Mobius_C1_HarbingersOfWar]"
    exit 1
}

mkdir -p "$(dirname "${OUT}")"

python3 - "${SOURCE}" "${OUT}" << 'PYEOF'
import re
import sys

source, out = sys.argv[1], sys.argv[2]

# The annotation precedes the field declaration:
#   @ClientString(id = 53, message = "Earned $s2 $s1(s).")
#   public static SystemMessageId EARNED_S2_S1_S;
pattern = re.compile(
    r'@ClientString\(id = (\d+), message = "((?:[^"\\]|\\.)*)"\)'
    r'\s*\n\s*public static SystemMessageId ([A-Za-z0-9_]+);')

messages = {}
java = open(source, encoding="utf-8").read()
for match in pattern.finditer(java):
    message_id = int(match.group(1))
    text = match.group(2).replace('\\"', '"').replace("\\\\", "\\")
    messages[message_id] = (match.group(3), text)

if len(messages) < 700:
    raise SystemExit(f"Error only {len(messages)} client strings parsed")

header = """// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT

// Code generated by tools/generate_system_messages.sh from the
// SystemMessageId.java @ClientString annotations of the Mobius C1
// sources. DO NOT EDIT.

package npcdata

// systemMessageCount reports the size of the generated dictionary.
const systemMessageCount = {count}

// systemMessages maps the SystemMessage packet id to the enum name and
// the client side text of the message. The $sN and $cN placeholders of
// the text are substituted with the packet parameters by the tracker.
var systemMessages = map[int32][2]string{{""".format(count=len(messages))

lines = [header]
for message_id in sorted(messages):
    name, text = messages[message_id]
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'\t{message_id}: {{"{name}", "{text}"}},')
lines.append("}")
lines.append("")
lines.append("""// SystemMessageText returns the client side text of a SystemMessage
// packet id. Unknown ids fall back to the plain id so the chat window
// still shows that something happened.
func SystemMessageText(id int32) string {
	if entry, ok := systemMessages[id]; ok {
		return entry[1]
	}

	return "system message " + itoa(int(id))
}

// SystemMessageName returns the SystemMessageId enum name of a packet
// id, empty when unknown.
func SystemMessageName(id int32) string {
	if entry, ok := systemMessages[id]; ok {
		return entry[0]
	}

	return ""
}

// itoa is a tiny int to string helper for the fallback text.
func itoa(value int) string {
	if value == 0 {
		return "0"
	}
	digits := ""
	negative := value < 0
	if negative {
		value = -value
	}
	for value > 0 {
		digits = string(rune('0'+value%10)) + digits
		value /= 10
	}
	if negative {
		digits = "-" + digits
	}

	return digits
}""")
lines.append("")

with open(out, "w", encoding="utf-8", newline="\n") as handle:
    handle.write("\n".join(lines))

import subprocess
import sys as _sys
subprocess.run(["gofmt", "-w", out], check=False)
print(f"Generated {len(messages)} system messages into {out}")
PYEOF
