#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
# SPDX-License-Identifier: MIT
#
# Regenerate the item price and weight dictionaries of the bot from the
# Mobius C1 data files. The sell price of an item on the Mobius server
# is fixed to referencePrice/2 (RequestSellItem), where referencePrice
# is the price attribute of the item stats, and the weight attribute is
# the unit weight. Both drive the junk ranking of the town trips: the
# bot sells duplicates and the lowest value per weight first. Missing
# attributes mean unknown (price 0, weight 0).
#
#   item: display id -> price, weight via data/stats/items/*.xml
#
# Usage: tools/generate_item_stats.sh [path/to/L2J_Mobius_C1_HarbingersOfWar]
# Output: internal/swarm/npcdata/item_stats.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOBIUS_C1="${1:-$(dirname "${SWARM_ROOT}")/l2j_mobius/L2J_Mobius_C1_HarbingersOfWar}"
OUT="${SCRIPT_DIR}/../internal/swarm/npcdata/item_stats.go"

STATS="${MOBIUS_C1}/dist/game/data/stats"
[ -d "${STATS}/items" ] || {
    echo "Error mobius item stats not found at ${STATS}/items"
    echo "Usage: $0 [path/to/L2J_Mobius_C1_HarbingersOfWar]"
    exit 1
}

mkdir -p "$(dirname "${OUT}")"

python3 - "${STATS}" "${OUT}" << 'PYEOF'
import glob
import re
import sys

stats, out = sys.argv[1], sys.argv[2]

# Item display id -> price, weight (from the item stats xml files). The
# set attribute order varies and every item element holds many sets, so
# the block of each item is sliced out and searched inside.
item_open_pattern = re.compile(r'<item\s+id="(\d+)"[^>]*>')
set_pattern = re.compile(r'<set\s+name="(\w+)"\s+val="([^"]*)"')
item_prices = {}
item_weights = {}
for path in glob.glob(f"{stats}/items/*.xml"):
    with open(path, encoding="utf-8") as handle:
        content = handle.read()
    matches = list(item_open_pattern.finditer(content))
    for index, match in enumerate(matches):
        item_id = int(match.group(1))
        block_end = (
            matches[index + 1].start()
            if index + 1 < len(matches)
            else len(content)
        )
        for name, value in set_pattern.findall(content, match.end(), block_end):
            if name == "price" and value.lstrip("-").isdigit():
                item_prices[item_id] = int(value)
            elif name == "weight" and value.isdigit():
                item_weights[item_id] = int(value)

def render_int64_map(values):
    if not values:
        return "\t{}\n"
    return "".join(f"\t{key}: {values[key]},\n" for key in sorted(values))

def render_int32_map(values):
    if not values:
        return "\t{}\n"
    return "".join(f"\t{key}: {values[key]},\n" for key in sorted(values))

content = (
    "// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>\n"
    "//\n"
    "// SPDX-License-Identifier: MIT\n"
    "\n"
    "// Code generated by tools/generate_item_stats.sh from the Mobius C1\n"
    "// data files. DO NOT EDIT.\n"
    "package npcdata\n"
    "\n"
    "// itemPrices maps the item display id to the reference price of the\n"
    "// item stats. The server sells items at referencePrice/2.\n"
    f"var itemPrices = map[int32]int64{{\n{render_int64_map(item_prices)}}}\n"
    "\n"
    "// itemWeights maps the item display id to the unit weight of the\n"
    "// item stats.\n"
    f"var itemWeights = map[int32]int32{{\n{render_int32_map(item_weights)}}}\n"
)
with open(out, "w", encoding="utf-8", newline="\n") as handle:
    handle.write(content)
print(
    f"wrote {len(item_prices)} item prices and "
    f"{len(item_weights)} item weights to {out}"
)
PYEOF

# The generated maps must be gofmt clean (aligned columns).
if command -v gofmt > /dev/null 2>&1; then
    gofmt -w "${OUT}"
fi
