#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
# SPDX-License-Identifier: MIT
#
# Regenerate the npc and item name dictionaries of the bot from the
# Mobius C1 data files. The game server sends NpcInfo packets with an
# empty name for most npcs (the classic client resolves names from
# NPCName-e.dat by the display template id) and DropItem packets carry
# only the item display id. This script reproduces both mappings:
#
#   npc:   template id (packet) - 1000000 -> display id
#          display id -> internal id via CT0_to_C4_ids.txt
#          internal id -> name via data/stats/npcs/*.xml
#   item:  display id -> name via data/stats/items/*.xml
#
# Usage: tools/generate_npc_names.sh [path/to/L2J_Mobius_C1_HarbingersOfWar]
# Output: internal/swarm/npcdata/names.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOBIUS_C1="${1:-$(dirname "${SWARM_ROOT}")/l2j_mobius/L2J_Mobius_C1_HarbingersOfWar}"
OUT="${SCRIPT_DIR}/../internal/swarm/npcdata/names.go"

STATS="${MOBIUS_C1}/dist/game/data/stats"
[ -f "${STATS}/npcs/CT0_to_C4_ids.txt" ] || {
    echo "Error mobius npc stats not found at ${STATS}"
    echo "Usage: $0 [path/to/L2J_Mobius_C1_HarbingersOfWar]"
    exit 1
}

mkdir -p "$(dirname "${OUT}")"

python3 - "${STATS}" "${OUT}" << 'PYEOF'
import glob
import re
import sys

stats, out = sys.argv[1], sys.argv[2]

# Internal npc id -> client display id (from CT0_to_C4_ids.txt).
internal_to_display = {}
with open(f"{stats}/npcs/CT0_to_C4_ids.txt", encoding="utf-8") as handle:
    for line in handle:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        internal, display = line.split(";")
        internal_to_display[int(internal)] = int(display)

# Internal npc id -> name (from the npc stats xml files).
npc_pattern = re.compile(r'<npc id="(\d+)"[^>]*?name="([^"]*)"')
npc_source = {}
for path in glob.glob(f"{stats}/npcs/*.xml"):
    with open(path, encoding="utf-8") as handle:
        for match in npc_pattern.finditer(handle.read()):
            npc_id, name = int(match.group(1)), match.group(2)
            if name:
                npc_source[npc_id] = name

# Display id -> name, the lookup the bot needs.
npc_names = {}
for internal, name in npc_source.items():
    display = internal_to_display.get(internal, internal)
    npc_names[display] = name

# Item display id -> name (from the item stats xml files).
item_pattern = re.compile(r'<item id="(\d+)"[^>]*?name="([^"]*)"')
item_names = {}
for path in glob.glob(f"{stats}/items/*.xml"):
    with open(path, encoding="utf-8") as handle:
        for match in item_pattern.finditer(handle.read()):
            item_id, name = int(match.group(1)), match.group(2)
            if name:
                item_names[item_id] = name

def render_map(values):
    if not values:
        return "\t{}\n"
    lines = []
    for key in sorted(values):
        name = values[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'\t{key}: "{name}",\n')
    return "".join(lines)

content = (
    "// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>\n"
    "//\n"
    "// SPDX-License-Identifier: MIT\n"
    "\n"
    "// Code generated by tools/generate_npc_names.sh from the Mobius C1\n"
    "// data files. DO NOT EDIT.\n"
    "package npcdata\n"
    "\n"
    "// npcNames maps the NpcInfo display template id (packet template id\n"
    "// minus 1000000) to the npc name.\n"
    f"var npcNames = map[int32]string{{\n{render_map(npc_names)}}}\n"
    "\n"
    "// itemNames maps the DropItem display id to the item name.\n"
    f"var itemNames = map[int32]string{{\n{render_map(item_names)}}}\n"
)
with open(out, "w", encoding="utf-8") as handle:
    handle.write(content)
print(
    f"wrote {len(npc_names)} npc names and "
    f"{len(item_names)} item names to {out}"
)
PYEOF
