#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
# SPDX-License-Identifier: MIT
#
# Regenerate the shop catalogs of the bot from the Mobius C1 data
# files: the buylists (data/buylists/*.xml) with their items and the
# merchants that own them, keyed by the packet template id (display
# id) of the NpcInfo packets through the CT0_to_C4 ids table. The
# shop strategy of the bot joins the catalogs with the item gear
# stats and prices at runtime.
#
#   buylist: file name id -> item ids, npc -> buylists
#   npc: spawn id -> packet display id via stats/npcs/CT0_to_C4_ids.txt
#
# Usage: tools/generate_shop_catalogs.sh [path/to/L2J_Mobius_C1_HarbingersOfWar]
# Output: internal/swarm/npcdata/shop_catalogs.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOBIUS_C1="${1:-$(dirname "${SWARM_ROOT}")/l2j_mobius/L2J_Mobius_C1_HarbingersOfWar}"
OUT="${SCRIPT_DIR}/../internal/swarm/npcdata/shop_catalogs.go"

DATA="${MOBIUS_C1}/dist/game/data"
[ -d "${DATA}/buylists" ] || {
    echo "Error mobius buylists not found at ${DATA}/buylists"
    echo "Usage: $0 [path/to/L2J_Mobius_C1_HarbingersOfWar]"
    exit 1
}

python3 - "${DATA}" "${OUT}" << 'PYEOF'
import glob
import json
import os
import re
import sys

data, out = sys.argv[1], sys.argv[2]

# Buylist id -> item ids (the buylist file name is the list id) and
# npc spawn id -> buylist ids (the <npcs> block of every file).
list_items = {}
npc_lists = {}
npc_pattern = re.compile(r'<npc>(\d+)</npc>')
item_pattern = re.compile(r'<item id="(\d+)"')
for path in sorted(glob.glob(f"{data}/buylists/*.xml")):
    list_id = int(os.path.basename(path).removesuffix(".xml"))
    with open(path, encoding="utf-8") as handle:
        content = handle.read()
    if list_id not in list_items:
        list_items[list_id] = []
    for match in npc_pattern.finditer(content):
        npc_lists.setdefault(int(match.group(1)), []).append(list_id)
    for match in item_pattern.finditer(content):
        item_id = int(match.group(1))
        if item_id not in list_items[list_id]:
            list_items[list_id].append(item_id)

# Npc spawn id -> packet display id (the CT0_to_C4 ids table maps the
# C4 npc id to the C1 client display id the NpcInfo packets carry).
npc_display = {}
with open(f"{data}/stats/npcs/CT0_to_C4_ids.txt", encoding="utf-8") as handle:
    for line in handle:
        parts = line.strip().split(";")
        if len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
            npc_display[int(parts[0])] = int(parts[1])

# Merchant template id (display id) -> buylist ids.
display_lists = {}
for npc_id, lists in sorted(npc_lists.items()):
    display_id = npc_display.get(npc_id)
    if display_id is None:
        continue
    display_lists[display_id] = sorted(lists)

def render_lists(values):
    parts = []
    for key in sorted(values):
        items = ", ".join(str(item) for item in values[key])
        parts.append(f"\t{key}: {{{items}}},\n")
    return "".join(parts)

def render_display_lists(values):
    parts = []
    for key in sorted(values):
        lists = ", ".join(str(list_id) for list_id in values[key])
        parts.append(f"\t{key}: {{{lists}}},\n")
    return "".join(parts)

content = (
    "// SPDX-FileCopyrightText: 2026 Melg Eight "
    "<public.melg8@gmail.com>\n"
    "//\n"
    "// SPDX-License-Identifier: MIT\n"
    "\n"
    "// Code generated by tools/generate_shop_catalogs.sh from the "
    "Mobius C1\n"
    "// data files. DO NOT EDIT.\n"
    "package npcdata\n"
    "\n"
    "// buyListItems maps the buylist id to the item ids the list "
    "sells.\n"
    f"var buyListItems = map[int32][]int32{{\n{render_lists(list_items)}}}\n"
    "\n"
    "// npcBuyLists maps the merchant packet template id (the display\n"
    "// id of the NpcInfo packets) to the buylist ids it sells.\n"
    f"var npcBuyLists = map[int32][]int32{{\n"
    f"{render_display_lists(display_lists)}}}\n"
)
with open(out, "w", encoding="utf-8", newline="\n") as handle:
    handle.write(content)
print(
    f"wrote {len(list_items)} buylists of "
    f"{len(display_lists)} merchants (of {len(npc_lists)} npc ids, "
    f"{len(npc_display)} display ids known) to {out}"
)
PYEOF

# The generated maps must be gofmt clean (aligned columns).
if command -v gofmt > /dev/null 2>&1; then
    gofmt -w "${OUT}"
fi
