#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
#
# SPDX-License-Identifier: MIT
#
# Regenerate the skill teacher dictionary of the bot from the Mobius
# C1 data files: which NPC of the deployment village teaches which
# class and where it stands. Three Mobius data sources feed the
# dictionary:
#
#   teach lists:  dist/game/data/SkillLearn.xml
#                 (npc id -> the class ids it can teach)
#   village spawn: dist/game/data/spawns/ElvenTerritory/
#                 ElvenVillageNPCs.xml (npc id -> spawn x/y/z and the
#                 name from the XML comment)
#   display ids:  dist/game/data/stats/npcs/CT0_to_C4_ids.txt
#                 (npc spawn id -> the display id the NpcInfo packets
#                 carry on the wire)
#
# Usage: tools/generate_skill_teachers.sh [path/to/L2J_Mobius_C1_HarbingersOfWar]
# Output: internal/swarm/npcdata/skill_teachers.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOBIUS_C1="${1:-$(dirname "${SWARM_ROOT}")/l2j_mobius/L2J_Mobius_C1_HarbingersOfWar}"
OUT="${SWARM_ROOT}/internal/swarm/npcdata/skill_teachers.go"

DATA="${MOBIUS_C1}/dist/game/data"
SPAWNS="${DATA}/spawns/ElvenTerritory/ElvenVillageNPCs.xml"
TEACH="${DATA}/SkillLearn.xml"
IDS="${DATA}/stats/npcs/CT0_to_C4_ids.txt"
for path in "${SPAWNS}" "${TEACH}" "${IDS}"; do
    [ -f "${path}" ] || {
        echo "Error mobius data not found at ${path}"
        echo "Usage: $0 [path/to/L2J_Mobius_C1_HarbingersOfWar]"
        exit 1
    }
done

mkdir -p "$(dirname "${OUT}")"

python3 - "${SPAWNS}" "${TEACH}" "${IDS}" "${OUT}" << 'PYEOF'
import os
import re
import sys

spawns_path, teach_path, ids_path, out = sys.argv[1:5]

# Village spawn id -> (name, x, y, z): the comment behind every npc
# entry carries the name, the attributes the standing point.
spawns = {}
text = open(spawns_path, encoding='utf-8').read()
for m in re.finditer(
        r'<npc id="(\d+)" x="(-?\d+)" y="(-?\d+)" z="(-?\d+)"[^>]*?>'
        r'\s*<!--\s*([^<]+?)\s*-->', text):
    npc_id = int(m.group(1))
    spawns[npc_id] = {
        'name': m.group(5),
        'x': int(m.group(2)),
        'y': int(m.group(3)),
        'z': int(m.group(4)),
    }

# Teach list npc id -> class ids.
teachers = {}
text = open(teach_path, encoding='utf-8').read()
for tm in re.finditer(
        r'<npc id="(\d+)">\s*<!--\s*([^<]+?)\s*-->(.*?)</npc>',
        text, re.S):
    npc_id, name = int(tm.group(1)), tm.group(2)
    for cm in re.finditer(r'<classId>(\d+)</classId>', tm.group(3)):
        class_id = int(cm.group(1))
        teachers.setdefault(class_id, []).append(npc_id)

# Npc spawn id -> packet display id (the CT0_to_C4 ids table).
wire_ids = {}
for line in open(ids_path, encoding='utf-8'):
    parts = line.strip().split(';')
    if len(parts) == 2 and parts[1].isdigit():
        wire_ids[int(parts[0])] = int(parts[1])

# ---------------------------------------------------------------- emit
def go_str(value):
    return '"%s"' % value.replace('\\', '\\\\').replace('"', '\\"')

lines = []
lines.append('// SPDX-FileCopyrightText: 2026 Melg Eight '
             '<public.melg8@gmail.com>')
lines.append('//')
lines.append('// SPDX-License-Identifier: MIT')
lines.append('')
lines.append('// Code generated by tools/generate_skill_teachers.sh. '
             'DO NOT EDIT.')
lines.append('')
lines.append('package npcdata')
lines.append('')
lines.append('// skillTeachers maps the class id to the teachers of the')
lines.append('// class that stand in the deployment village (the Elven')
lines.append('// Village spawns): the packet display id the NpcInfo packet')
lines.append('// carries, the name and the spawn point. TeachersOfClass in')
lines.append('// skills.go answers the lookup.')
lines.append('var skillTeachers = map[int32][]TeacherNPC{')
classes = sorted(c for c in teachers if any(npc in spawns
                                            for npc in teachers[c]))
for class_id in classes:
    entries = [npc for npc in teachers[class_id] if npc in spawns]
    if not entries:
        continue
    lines.append('\t%d: {' % class_id)
    for npc_id in sorted(set(entries)):
        spawn = spawns[npc_id]
        display = wire_ids.get(npc_id, npc_id)
        lines.append('\t\t{TemplateID: %d, Name: %s, X: %d, Y: %d, Z: %d},'
                     % (display, go_str(spawn['name']),
                        spawn['x'], spawn['y'], spawn['z']))
    lines.append('\t},')
lines.append('}')
lines.append('')

with open(out, 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(lines))

npc_total = sum(len(set(n for v in teachers.values() for n in v
                        if n in spawns)) for _ in [0])
npc_total = len({n for v in teachers.values() for n in v if n in spawns})
print('teach lists: %d classes of the village, %d teacher npcs'
      % (len(classes), npc_total))
print('written: %s' % out)
PYEOF

if command -v gofmt >/dev/null 2>&1; then
    gofmt -w "${OUT}"
fi
