#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
# SPDX-License-Identifier: MIT
#
# Generate the world merchant spawn table of the bot from the Mobius C1
# data files: every spawn of every npc that owns a buylist, keyed by the
# packet template id (the display id of the NpcInfo packets) through the
# CT0_to_C4 ids table. The counterprobe tool (-mode world) derives and
# verifies the customer stand point of every spawn from this table and
# the trip machinery resolves the approach point of any merchant id
# through it.
#
#   spawn: <npc id= x= y= z= heading= /> rows of the spawn xml files
#   npc:   spawn id -> packet display id via stats/npcs/CT0_to_C4_ids.txt
#   shop:  the buylist owners (the display ids of the generated
#          shop_catalogs.go npcBuyLists map) decide who is a merchant
#
# Usage: tools/generate_merchant_spawns.sh [path/to/L2J_Mobius_C1_HarbingersOfWar]
# Output: internal/swarm/npcdata/merchant_spawns.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOBIUS_C1="${1:-$(dirname "${SWARM_ROOT}")/l2j_mobius/L2J_Mobius_C1_HarbingersOfWar}"
OUT="${SCRIPT_DIR}/../internal/swarm/npcdata/merchant_spawns.go"

DATA="${MOBIUS_C1}/dist/game/data"
[ -d "${DATA}/spawns" ] || {
    echo "Error mobius spawns not found at ${DATA}/spawns"
    echo "Usage: $0 [path/to/L2J_Mobius_C1_HarbingersOfWar]"
    exit 1
}

python3 - "${DATA}" "${OUT}" << 'PYEOF'
import glob
import os
import re
import sys

data, out = sys.argv[1], sys.argv[2]

# The merchant display ids the bot catalogs know (the npcBuyLists keys
# of the generated shop catalogs).
catalog = open(
    f"{os.path.dirname(os.path.abspath(out))}/shop_catalogs.go",
    encoding="utf-8",
).read()
block = catalog.split("var npcBuyLists = map[int32][]int32{", 1)[1]
merchant_display_ids = set(
    int(m) for m in re.findall(r"^\s*(\d+):\s*\{", block, re.M)
)

# C4 npc id -> packet display id (the CT0_to_C4 table maps the C4 npc
# id to the C1 client display id the NpcInfo packets carry).
c4_to_display = {}
with open(f"{data}/stats/npcs/CT0_to_C4_ids.txt", encoding="utf-8") as h:
    for line in h:
        parts = line.strip().split(";")
        if len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
            display = int(parts[1])
            if display in merchant_display_ids:
                c4_to_display[int(parts[0])] = display

# The spawn rows: every <npc id=.. x=.. y=.. z=.. heading=.. /> of the
# spawn xml tree, the npc name rides the trailing comment.
spawn_pattern = re.compile(
    r'<npc id="(\d+)" x="(-?\d+)" y="(-?\d+)" z="(-?\d+)" '
    r'heading="(-?\d+)"[^>]*/>\s*(?:<!--\s*(.*?)\s*-->)?'
)

rows = {}
for path in sorted(glob.glob(f"{data}/spawns/**/*.xml", recursive=True)):
    content = open(path, encoding="utf-8").read()
    for m in spawn_pattern.finditer(content):
        c4_id = int(m.group(1))
        display = c4_to_display.get(c4_id)
        if display is None:
            continue
        name = (m.group(6) or "").strip()
        rows[display] = (name, int(m.group(2)), int(m.group(3)),
                         int(m.group(4)), int(m.group(5)))

def render_rows(values):
    parts = []
    for key in sorted(values):
        name, x, y, z, heading = values[key]
        parts.append(
            f"\t{key}: {{Name: \"{name}\", X: {x}, Y: {y}, Z: {z}, "
            f"Heading: {heading}}},\n"
        )
    return "".join(parts)

content = (
    "// SPDX-FileCopyrightText: 2026 Melg Eight "
    "<public.melg8@gmail.com>\n"
    "//\n"
    "// SPDX-License-Identifier: MIT\n"
    "\n"
    "// Code generated by tools/generate_merchant_spawns.sh. DO NOT EDIT.\n"
    "//\n"
    "package npcdata\n"
    "\n"
    "import \"sort\"\n"
    "\n"
    "// MerchantSpawn is one world spawn of a shop merchant: the spawn\n"
    "// position and the facing heading of the Mobius C1 spawn data,\n"
    "// keyed by the packet template id (the display id of the NpcInfo\n"
    "// packets, the key of the generated buylist catalogs).\n"
    "type MerchantSpawn struct {\n"
    "    Name    string\n"
    "    X       int32\n"
    "    Y       int32\n"
    "    Z       int32\n"
    "    Heading int32\n"
    "}\n"
    "\n"
    "// merchantSpawns holds every world spawn of every npc the\n"
    "// generated buylist catalogs know (one spawn per display id in the\n"
    "// C1 spawn data). The counterprobe tool derives the customer stand\n"
    "// points from it and the trip machinery resolves the approach\n"
    "// point of a merchant id through it.\n"
    "var merchantSpawns = map[int32]MerchantSpawn{\n"
    f"{render_rows(rows)}}}\n"
    "\n"
    "// MerchantSpawnOf resolves the world spawn of the merchant packet\n"
    "// template id. It reports false when the npc sells nothing through\n"
    "// the catalogs or the spawn data spawns it nowhere.\n"
    "func MerchantSpawnOf(templateID int32) (MerchantSpawn, bool) {\n"
    "    spawn, ok := merchantSpawns[templateID]\n"
    "\n"
    "    return spawn, ok\n"
    "}\n"
    "\n"
    "// MerchantSpawnCount returns the number of the world merchant\n"
    "// spawns the table carries.\n"
    "func MerchantSpawnCount() int {\n"
    "    return len(merchantSpawns)\n"
    "}\n"
    "\n"
    "// MerchantTemplateIDs returns the packet template ids of every\n"
    "// world merchant spawn, sorted (the enumeration key of the\n"
    "// counterprobe stand derivation).\n"
    "func MerchantTemplateIDs() []int32 {\n"
    "    ids := make([]int32, 0, len(merchantSpawns))\n"
    "    for id := range merchantSpawns {\n"
    "        ids = append(ids, id)\n"
    "    }\n"
    "    sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })\n"
    "\n"
    "    return ids\n"
    "}\n"
)
with open(out, "w", encoding="utf-8", newline="\n") as handle:
    handle.write(content)
print(
    f"wrote {len(rows)} merchant spawns "
    f"(of {len(merchant_display_ids)} catalog merchants) to {out}"
)
PYEOF

# The generated maps must be gofmt clean (aligned columns).
if command -v gofmt > /dev/null 2>&1; then
    gofmt -w "${OUT}"
fi
