#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
# SPDX-License-Identifier: MIT
#
# Regenerate the item icon dictionary of the bot from the Mobius C1
# item stats and the icon pack. The C1 server stats carry the canonical
# icon name of every item (set name="icon" val="icon.xxx"), which works
# for 4044 of 4222 C1 items directly; the low grade starter armor icons
# were renamed by the later clients, so the remaining ids resolve
# through the l2walker Interlude item database (data/db/db.sqlite of a
# l2walker checkout) by the same item id.
#
#   server stats: dist/game/data/stats/items/*.xml (item id, icon)
#   icon pack:    data/icons/<name>.png of this repository
#   renames:      db.sqlite etcitem table (optional path argument)
#
# Usage: tools/generate_item_icons.sh [mobius_c1_root] [l2walker_root]
# Output: internal/swarm/npcdata/item_icons.go

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MOBIUS_C1="${1:-$(dirname "${SWARM_ROOT}")/l2j_mobius/L2J_Mobius_C1_HarbingersOfWar}"
L2WALKER="${2:-${SCRIPT_DIR}/../../l2walker_master}"
OUT="${SCRIPT_DIR}/../internal/swarm/npcdata/item_icons.go"
ICONS="${SWARM_ROOT}/data/icons"

STATS="${MOBIUS_C1}/dist/game/data/stats"
[ -d "${STATS}/items" ] || {
    echo "Error mobius item stats not found at ${STATS}/items"
    echo "Usage: $0 [mobius_c1_root] [l2walker_root]"
    exit 1
}
[ -d "${ICONS}" ] || {
    echo "Error icon pack not found at ${ICONS}"
    exit 1
}

mkdir -p "$(dirname "${OUT}")"

python3 - "${STATS}" "${ICONS}" "${L2WALKER}" "${OUT}" << 'PYEOF'
import glob
import os
import re
import sqlite3
import sys

stats, icons, l2walker, out = sys.argv[1:5]

# Item id -> canonical C1 icon name of the server stats.
c1_icons = {}
for path in glob.glob(os.path.join(stats, 'items', '*.xml')):
    text = open(path, encoding='utf-8').read()
    for m in re.finditer(r'<item id="(\d+)"[^>]*?>(.*?)(?=<item |\Z)', text, re.S):
        item_id, body = int(m.group(1)), m.group(2)
        im = re.search(r'name="icon" val="([^"]+)"', body)
        if im:
            c1_icons[item_id] = im.group(1)[len('icon.'):]

pack = set(f[:-4] for f in os.listdir(icons) if f.endswith('.png'))

# The renamed starter icons: same item id in the l2walker Interlude
# database, different icon name that exists in the pack.
rename_db = os.path.join(l2walker, 'data', 'db', 'db.sqlite')
renamed = 0
if os.path.isfile(rename_db):
    db = sqlite3.connect(rename_db)
    try:
        cur = db.cursor()
        for item_id, icon in list(c1_icons.items()):
            if icon in pack:
                continue
            row = cur.execute(
                'SELECT icon FROM etcitem WHERE item_id=?', (item_id,)
            ).fetchone()
            if row and row[0]:
                base = row[0]
                if base.startswith('icon.'):
                    base = base[len('icon.'):]
                if base in pack:
                    c1_icons[item_id] = base
                    renamed += 1
    finally:
        db.close()

direct = sum(1 for icon in c1_icons.values() if icon in pack)
unresolved = {k: v for k, v in c1_icons.items() if v not in pack}
print('items:', len(c1_icons), 'direct:', direct,
      'renamed:', renamed, 'unresolved:', len(unresolved))
for key in sorted(unresolved)[:10]:
    print('  unresolved:', key, unresolved[key])
if unresolved:
    print('Error unresolved icons remain, fix the pack first')
    sys.exit(1)

with open(out, 'w', encoding='utf-8') as f:
    f.write('''// SPDX-FileCopyrightText: 2026 Melg Eight <public.melg8@gmail.com>
//
// SPDX-License-Identifier: MIT
//
// Code generated by tools/generate_item_icons.sh. DO NOT EDIT.

package npcdata

// itemIcons maps the item display id to the icon file name (without
// extension) of the icon pack in data/icons. Generated by
// tools/generate_item_icons.sh from the Mobius C1 item stats and the
// l2walker icon pack: the C1 icon names cover most items directly, the
// renamed starter armor icons resolve through the l2walker Interlude
// item database by the same item id (see data/icons/Readme.txt).

var itemIcons = map[int32]string{
''')
    for item_id in sorted(c1_icons):
        f.write('\t%d: "%s",\n' % (item_id, c1_icons[item_id]))
    f.write('}\n')
print('written:', out)
PYEOF

gofmt_out="${OUT}"
if command -v gofmt >/dev/null 2>&1; then
    gofmt -w "${gofmt_out}"
fi
echo "done"
